import AsyncStorage from '@react-native-async-storage/async-storage';
import { Transaction, dateToString, CATEGORY_TYPE_MAP } from '@/constants/config';

const STORAGE_KEY = 'finance_transactions';

function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2);
}

// Full sample data from user's Excel sheet
const SAMPLE_TRANSACTIONS: Transaction[] = [
  // January 2026
  { id: generateId(), date: '01 Jan 2026', description: 'Uber late night - NYE', category: 'Life Infrastructure', amount: 450, paymentMode: 'UPI', type: 'Need', notes: 'NYE cab home' },
  { id: generateId(), date: '01 Jan 2026', description: 'Brunch out with friends', category: 'Lifestyle Enjoyment', amount: 950, paymentMode: 'Credit Card', type: 'Want', notes: 'New year brunch' },
  { id: generateId(), date: '01 Jan 2026', description: 'Swiggy dinner', category: 'Lifestyle Enjoyment', amount: 380, paymentMode: 'UPI', type: 'Want', notes: 'Too tired to cook' },
  { id: generateId(), date: '02 Jan 2026', description: 'House Rent', category: 'Life Infrastructure', amount: 12000, paymentMode: 'Bank Transfer', type: 'Need', notes: 'Monthly rent' },
  { id: generateId(), date: '02 Jan 2026', description: 'Groceries - BigBasket', category: 'Life Infrastructure', amount: 1600, paymentMode: 'UPI', type: 'Need', notes: 'Monthly stock' },
  { id: generateId(), date: '02 Jan 2026', description: 'Swiggy lunch', category: 'Lifestyle Enjoyment', amount: 320, paymentMode: 'UPI', type: 'Want', notes: 'Office lunch' },
  { id: generateId(), date: '02 Jan 2026', description: 'Chai tapri', category: 'Lifestyle Enjoyment', amount: 30, paymentMode: 'Cash', type: 'Want', notes: 'Evening chai' },
  { id: generateId(), date: '03 Jan 2026', description: 'Myntra sale - clothes', category: 'Lifestyle Enjoyment', amount: 3200, paymentMode: 'Credit Card', type: 'Want', notes: 'New year sale haul' },
  { id: generateId(), date: '03 Jan 2026', description: 'Movie + popcorn', category: 'Lifestyle Enjoyment', amount: 800, paymentMode: 'UPI', type: 'Want', notes: 'Weekend movie' },
  { id: generateId(), date: '03 Jan 2026', description: 'Dinner out - Barbeque Nation', category: 'Lifestyle Enjoyment', amount: 1100, paymentMode: 'Credit Card', type: 'Want', notes: 'Saturday dinner' },
  { id: generateId(), date: '03 Jan 2026', description: 'Uber rides', category: 'Life Infrastructure', amount: 280, paymentMode: 'UPI', type: 'Need', notes: 'Mall + movie' },
  { id: generateId(), date: '04 Jan 2026', description: 'Zomato brunch', category: 'Lifestyle Enjoyment', amount: 550, paymentMode: 'UPI', type: 'Want', notes: 'Lazy Sunday' },
  { id: generateId(), date: '04 Jan 2026', description: 'Groceries - Zepto', category: 'Life Infrastructure', amount: 420, paymentMode: 'UPI', type: 'Need', notes: 'Quick essentials' },
  { id: generateId(), date: '04 Jan 2026', description: 'Amazon - Bluetooth speaker', category: 'Lifestyle Enjoyment', amount: 1800, paymentMode: 'Credit Card', type: 'Want', notes: 'Impulse buy' },
  { id: generateId(), date: '05 Jan 2026', description: 'Metro Card Recharge', category: 'Life Infrastructure', amount: 500, paymentMode: 'UPI', type: 'Need', notes: 'Monthly commute' },
  { id: generateId(), date: '05 Jan 2026', description: 'Mobile Recharge', category: 'Life Infrastructure', amount: 299, paymentMode: 'UPI', type: 'Need', notes: 'Airtel plan' },
  { id: generateId(), date: '05 Jan 2026', description: 'Coffee - Starbucks', category: 'Lifestyle Enjoyment', amount: 380, paymentMode: 'UPI', type: 'Want', notes: 'Monday blues' },
  { id: generateId(), date: '05 Jan 2026', description: 'Swiggy dinner', category: 'Lifestyle Enjoyment', amount: 290, paymentMode: 'UPI', type: 'Want', notes: 'Tired after work' },
  { id: generateId(), date: '06 Jan 2026', description: 'Gym Membership', category: 'Performance & Growth', amount: 1500, paymentMode: 'Debit Card', type: 'Need', notes: 'Monthly gym' },
  { id: generateId(), date: '06 Jan 2026', description: 'Uber to office', category: 'Life Infrastructure', amount: 200, paymentMode: 'UPI', type: 'Need', notes: 'Running late' },
  { id: generateId(), date: '06 Jan 2026', description: 'Lunch canteen', category: 'Lifestyle Enjoyment', amount: 130, paymentMode: 'Cash', type: 'Want', notes: 'Office lunch' },
  { id: generateId(), date: '07 Jan 2026', description: 'Netflix', category: 'Lifestyle Enjoyment', amount: 199, paymentMode: 'Credit Card', type: 'Want', notes: 'Monthly sub' },
  { id: generateId(), date: '07 Jan 2026', description: 'Spotify', category: 'Lifestyle Enjoyment', amount: 119, paymentMode: 'Credit Card', type: 'Want', notes: 'Monthly sub' },
  { id: generateId(), date: '07 Jan 2026', description: 'Zepto snacks', category: 'Life Infrastructure', amount: 350, paymentMode: 'UPI', type: 'Need', notes: 'Chips, drinks' },
  { id: generateId(), date: '07 Jan 2026', description: 'Auto rickshaw', category: 'Life Infrastructure', amount: 60, paymentMode: 'Cash', type: 'Need', notes: 'Short ride' },
  { id: generateId(), date: '08 Jan 2026', description: 'Electricity Bill', category: 'Life Infrastructure', amount: 1400, paymentMode: 'UPI', type: 'Need', notes: 'Jan bill' },
  { id: generateId(), date: '08 Jan 2026', description: 'Drinks with friends', category: 'Lifestyle Enjoyment', amount: 1600, paymentMode: 'Credit Card', type: 'Want', notes: 'Thursday night out' },
  { id: generateId(), date: '08 Jan 2026', description: 'Uber late night', category: 'Life Infrastructure', amount: 350, paymentMode: 'UPI', type: 'Need', notes: 'Cab home' },
  { id: generateId(), date: '09 Jan 2026', description: 'Petrol', category: 'Life Infrastructure', amount: 800, paymentMode: 'Debit Card', type: 'Need', notes: 'Bike fuel' },
  { id: generateId(), date: '09 Jan 2026', description: 'Pizza Hut dinner', category: 'Lifestyle Enjoyment', amount: 650, paymentMode: 'UPI', type: 'Want', notes: 'TGIF' },
  { id: generateId(), date: '09 Jan 2026', description: 'Chai + samosa', category: 'Lifestyle Enjoyment', amount: 50, paymentMode: 'Cash', type: 'Want', notes: 'Office snack' },
  { id: generateId(), date: '10 Jan 2026', description: 'Shopping - Nike shoes', category: 'Lifestyle Enjoyment', amount: 4500, paymentMode: 'Credit Card', type: 'Want', notes: 'New kicks' },
  { id: generateId(), date: '10 Jan 2026', description: 'Zomato dinner', category: 'Lifestyle Enjoyment', amount: 700, paymentMode: 'UPI', type: 'Want', notes: 'Korean food' },
  { id: generateId(), date: '10 Jan 2026', description: 'Uber rides', category: 'Life Infrastructure', amount: 300, paymentMode: 'UPI', type: 'Need', notes: 'Shopping trip' },
  { id: generateId(), date: '11 Jan 2026', description: 'Groceries - DMart', category: 'Life Infrastructure', amount: 1100, paymentMode: 'Cash', type: 'Need', notes: 'Weekly buy' },
  { id: generateId(), date: '11 Jan 2026', description: 'Swiggy lunch', category: 'Lifestyle Enjoyment', amount: 280, paymentMode: 'UPI', type: 'Want', notes: 'Lazy day' },
  { id: generateId(), date: '11 Jan 2026', description: 'Ice cream', category: 'Lifestyle Enjoyment', amount: 200, paymentMode: 'UPI', type: 'Want', notes: 'Baskin Robbins' },
  { id: generateId(), date: '12 Jan 2026', description: 'Uber to office', category: 'Life Infrastructure', amount: 180, paymentMode: 'UPI', type: 'Need', notes: 'Late again' },
  { id: generateId(), date: '12 Jan 2026', description: 'Lunch with colleague', category: 'Relationships & Generosity', amount: 450, paymentMode: 'UPI', type: 'Want', notes: 'Treat lunch' },
  { id: generateId(), date: '13 Jan 2026', description: 'Internet Bill', category: 'Life Infrastructure', amount: 799, paymentMode: 'UPI', type: 'Need', notes: 'Broadband' },
  { id: generateId(), date: '13 Jan 2026', description: 'Chai tapri', category: 'Lifestyle Enjoyment', amount: 30, paymentMode: 'Cash', type: 'Want', notes: 'Morning chai' },
  { id: generateId(), date: '13 Jan 2026', description: 'Swiggy dinner', category: 'Lifestyle Enjoyment', amount: 350, paymentMode: 'UPI', type: 'Want', notes: 'Butter chicken' },
  { id: generateId(), date: '14 Jan 2026', description: 'Water Bill', category: 'Life Infrastructure', amount: 200, paymentMode: 'UPI', type: 'Need', notes: 'Quarterly' },
  { id: generateId(), date: '14 Jan 2026', description: 'Amazon - Gaming mouse', category: 'Lifestyle Enjoyment', amount: 900, paymentMode: 'Credit Card', type: 'Want', notes: 'Impulse' },
  { id: generateId(), date: '14 Jan 2026', description: 'Street food', category: 'Lifestyle Enjoyment', amount: 120, paymentMode: 'Cash', type: 'Want', notes: 'Pani puri' },
  { id: generateId(), date: '15 Jan 2026', description: 'SIP - Mutual Fund', category: 'Future Me', amount: 2000, paymentMode: 'Bank Transfer', type: 'Saving', notes: 'Skipped last 2 months' },
  { id: generateId(), date: '15 Jan 2026', description: 'Groceries - Zepto', category: 'Life Infrastructure', amount: 380, paymentMode: 'UPI', type: 'Need', notes: 'Milk bread eggs' },
  { id: generateId(), date: '15 Jan 2026', description: 'Dinner out', category: 'Lifestyle Enjoyment', amount: 800, paymentMode: 'Credit Card', type: 'Want', notes: 'Midweek treat' },
  { id: generateId(), date: '16 Jan 2026', description: 'Uber rides', category: 'Life Infrastructure', amount: 220, paymentMode: 'UPI', type: 'Need', notes: 'Commute' },
  { id: generateId(), date: '16 Jan 2026', description: 'Drinks + karaoke', category: 'Lifestyle Enjoyment', amount: 1400, paymentMode: 'Credit Card', type: 'Want', notes: 'Friday night' },
  { id: generateId(), date: '17 Jan 2026', description: 'Brunch cafe', category: 'Lifestyle Enjoyment', amount: 750, paymentMode: 'UPI', type: 'Want', notes: 'Weekend brunch' },
  { id: generateId(), date: '17 Jan 2026', description: 'Flipkart - Earbuds', category: 'Lifestyle Enjoyment', amount: 1200, paymentMode: 'Credit Card', type: 'Want', notes: 'Lost old ones' },
  { id: generateId(), date: '17 Jan 2026', description: 'Zomato dinner', category: 'Lifestyle Enjoyment', amount: 480, paymentMode: 'UPI', type: 'Want', notes: 'Biryani' },
  { id: generateId(), date: '18 Jan 2026', description: 'Groceries - BigBasket', category: 'Life Infrastructure', amount: 900, paymentMode: 'UPI', type: 'Need', notes: 'Restock' },
  { id: generateId(), date: '18 Jan 2026', description: 'Cooking gas', category: 'Life Infrastructure', amount: 900, paymentMode: 'UPI', type: 'Need', notes: 'Cylinder refill' },
  { id: generateId(), date: '18 Jan 2026', description: 'Swiggy ice cream', category: 'Lifestyle Enjoyment', amount: 180, paymentMode: 'UPI', type: 'Want', notes: 'Dessert craving' },
  { id: generateId(), date: '19 Jan 2026', description: 'Auto to metro', category: 'Life Infrastructure', amount: 40, paymentMode: 'Cash', type: 'Need', notes: 'Commute' },
  { id: generateId(), date: '19 Jan 2026', description: 'Chai + vada pav', category: 'Lifestyle Enjoyment', amount: 60, paymentMode: 'Cash', type: 'Want', notes: 'Lunch' },
  { id: generateId(), date: '20 Jan 2026', description: 'Uber rides', category: 'Life Infrastructure', amount: 190, paymentMode: 'UPI', type: 'Need', notes: 'Rain day' },
  { id: generateId(), date: '20 Jan 2026', description: 'Swiggy lunch', category: 'Lifestyle Enjoyment', amount: 260, paymentMode: 'UPI', type: 'Want', notes: 'Office order' },
  { id: generateId(), date: '21 Jan 2026', description: 'Groceries - Zepto', category: 'Life Infrastructure', amount: 320, paymentMode: 'UPI', type: 'Need', notes: 'Quick run' },
  { id: generateId(), date: '21 Jan 2026', description: 'Haircut + grooming', category: 'Lifestyle Enjoyment', amount: 500, paymentMode: 'Cash', type: 'Want', notes: 'Salon visit' },
  { id: generateId(), date: '22 Jan 2026', description: 'Team dinner', category: 'Relationships & Generosity', amount: 600, paymentMode: 'UPI', type: 'Want', notes: 'Office team' },
  { id: generateId(), date: '22 Jan 2026', description: 'Uber home', category: 'Life Infrastructure', amount: 250, paymentMode: 'UPI', type: 'Need', notes: 'Late night' },
  { id: generateId(), date: '23 Jan 2026', description: 'Petrol', category: 'Life Infrastructure', amount: 700, paymentMode: 'Debit Card', type: 'Need', notes: 'Bike fuel' },
  { id: generateId(), date: '23 Jan 2026', description: 'Swiggy dinner', category: 'Lifestyle Enjoyment', amount: 340, paymentMode: 'UPI', type: 'Want', notes: 'Chinese food' },
  { id: generateId(), date: '24 Jan 2026', description: 'Concert tickets', category: 'Lifestyle Enjoyment', amount: 1500, paymentMode: 'Credit Card', type: 'Want', notes: 'Weekend plan' },
  { id: generateId(), date: '24 Jan 2026', description: 'Dinner out post concert', category: 'Lifestyle Enjoyment', amount: 900, paymentMode: 'Credit Card', type: 'Want', notes: 'Late dinner' },
  { id: generateId(), date: '24 Jan 2026', description: 'Uber', category: 'Life Infrastructure', amount: 350, paymentMode: 'UPI', type: 'Need', notes: 'Concert venue' },
  { id: generateId(), date: '25 Jan 2026', description: 'Groceries - DMart', category: 'Life Infrastructure', amount: 800, paymentMode: 'Cash', type: 'Need', notes: 'Weekly buy' },
  { id: generateId(), date: '25 Jan 2026', description: 'Laundry', category: 'Life Infrastructure', amount: 200, paymentMode: 'UPI', type: 'Need', notes: 'Dry cleaning' },
  { id: generateId(), date: '26 Jan 2026', description: 'Brunch out', category: 'Lifestyle Enjoyment', amount: 650, paymentMode: 'UPI', type: 'Want', notes: 'Holiday brunch' },
  { id: generateId(), date: '26 Jan 2026', description: 'Shopping - jacket', category: 'Lifestyle Enjoyment', amount: 1800, paymentMode: 'Credit Card', type: 'Want', notes: 'Winter sale' },
  { id: generateId(), date: '27 Jan 2026', description: 'Metro recharge', category: 'Life Infrastructure', amount: 200, paymentMode: 'UPI', type: 'Need', notes: 'Top up' },
  { id: generateId(), date: '27 Jan 2026', description: 'Chai tapri', category: 'Lifestyle Enjoyment', amount: 30, paymentMode: 'Cash', type: 'Want', notes: 'Chai break' },
  { id: generateId(), date: '28 Jan 2026', description: 'Groceries - Zepto', category: 'Life Infrastructure', amount: 290, paymentMode: 'UPI', type: 'Need', notes: 'Essentials' },
  { id: generateId(), date: '28 Jan 2026', description: 'Swiggy lunch', category: 'Lifestyle Enjoyment', amount: 230, paymentMode: 'UPI', type: 'Want', notes: 'Dal makhani' },
  { id: generateId(), date: '29 Jan 2026', description: 'Medicine', category: 'Life Infrastructure', amount: 350, paymentMode: 'Cash', type: 'Need', notes: 'Cold meds' },
  { id: generateId(), date: '29 Jan 2026', description: 'Auto', category: 'Life Infrastructure', amount: 50, paymentMode: 'Cash', type: 'Need', notes: 'Short ride' },
  { id: generateId(), date: '30 Jan 2026', description: 'Uber', category: 'Life Infrastructure', amount: 170, paymentMode: 'UPI', type: 'Need', notes: 'Commute' },
  { id: generateId(), date: '30 Jan 2026', description: 'Canteen lunch', category: 'Lifestyle Enjoyment', amount: 120, paymentMode: 'Cash', type: 'Want', notes: 'Office' },
  { id: generateId(), date: '31 Jan 2026', description: 'Swiggy dinner', category: 'Lifestyle Enjoyment', amount: 300, paymentMode: 'UPI', type: 'Want', notes: 'Month end' },
  { id: generateId(), date: '31 Jan 2026', description: 'Paan + chai', category: 'Lifestyle Enjoyment', amount: 50, paymentMode: 'Cash', type: 'Want', notes: 'Night walk' },

  // February 2026
  { id: generateId(), date: '01 Feb 2026', description: 'House Rent', category: 'Life Infrastructure', amount: 12000, paymentMode: 'Bank Transfer', type: 'Need', notes: 'Monthly rent' },
  { id: generateId(), date: '01 Feb 2026', description: 'Groceries - BigBasket', category: 'Life Infrastructure', amount: 1500, paymentMode: 'UPI', type: 'Need', notes: 'Monthly stock' },
  { id: generateId(), date: '01 Feb 2026', description: 'Chai tapri', category: 'Lifestyle Enjoyment', amount: 30, paymentMode: 'Cash', type: 'Want', notes: 'Morning chai' },
  { id: generateId(), date: '02 Feb 2026', description: 'Metro Card Recharge', category: 'Life Infrastructure', amount: 500, paymentMode: 'UPI', type: 'Need', notes: 'Monthly pass' },
  { id: generateId(), date: '02 Feb 2026', description: 'Mobile Recharge', category: 'Life Infrastructure', amount: 299, paymentMode: 'UPI', type: 'Need', notes: 'Airtel plan' },
  { id: generateId(), date: '02 Feb 2026', description: 'Swiggy lunch', category: 'Lifestyle Enjoyment', amount: 280, paymentMode: 'UPI', type: 'Want', notes: 'Office order' },
  { id: generateId(), date: '03 Feb 2026', description: 'Gym Membership', category: 'Performance & Growth', amount: 1500, paymentMode: 'Debit Card', type: 'Need', notes: 'Monthly gym' },
  { id: generateId(), date: '03 Feb 2026', description: 'Uber to office', category: 'Life Infrastructure', amount: 180, paymentMode: 'UPI', type: 'Need', notes: 'Late start' },
  { id: generateId(), date: '03 Feb 2026', description: 'Chai + samosa', category: 'Lifestyle Enjoyment', amount: 50, paymentMode: 'Cash', type: 'Want', notes: 'Snack break' },
  { id: generateId(), date: '04 Feb 2026', description: 'Netflix', category: 'Lifestyle Enjoyment', amount: 199, paymentMode: 'Credit Card', type: 'Want', notes: 'Monthly sub' },
  { id: generateId(), date: '04 Feb 2026', description: 'Groceries - Zepto', category: 'Life Infrastructure', amount: 380, paymentMode: 'UPI', type: 'Need', notes: 'Fruits veggies' },
  { id: generateId(), date: '04 Feb 2026', description: 'Canteen lunch', category: 'Lifestyle Enjoyment', amount: 120, paymentMode: 'Cash', type: 'Want', notes: 'Office' },
  { id: generateId(), date: '05 Feb 2026', description: 'Electricity Bill', category: 'Life Infrastructure', amount: 1300, paymentMode: 'UPI', type: 'Need', notes: 'Feb bill' },
  { id: generateId(), date: '05 Feb 2026', description: 'Dinner with college friends', category: 'Relationships & Generosity', amount: 1100, paymentMode: 'UPI', type: 'Want', notes: 'Reunion dinner' },
  { id: generateId(), date: '05 Feb 2026', description: 'Uber home', category: 'Life Infrastructure', amount: 280, paymentMode: 'UPI', type: 'Need', notes: 'Late cab' },
  { id: generateId(), date: '06 Feb 2026', description: 'Petrol', category: 'Life Infrastructure', amount: 800, paymentMode: 'Debit Card', type: 'Need', notes: 'Bike fuel' },
  { id: generateId(), date: '06 Feb 2026', description: 'Coffee - Third Wave', category: 'Lifestyle Enjoyment', amount: 300, paymentMode: 'UPI', type: 'Want', notes: 'Friday coffee' },
  { id: generateId(), date: '06 Feb 2026', description: 'Zomato dinner', category: 'Lifestyle Enjoyment', amount: 450, paymentMode: 'UPI', type: 'Want', notes: 'Pizza night' },
  { id: generateId(), date: '07 Feb 2026', description: 'SIP - Mutual Fund', category: 'Future Me', amount: 3000, paymentMode: 'Bank Transfer', type: 'Saving', notes: 'Trying to be better' },
  { id: generateId(), date: '07 Feb 2026', description: 'Movie tickets + snacks', category: 'Lifestyle Enjoyment', amount: 850, paymentMode: 'UPI', type: 'Want', notes: 'Weekend movie' },
  { id: generateId(), date: '07 Feb 2026', description: 'Shopping - t-shirts', category: 'Lifestyle Enjoyment', amount: 1500, paymentMode: 'Credit Card', type: 'Want', notes: 'Zara sale' },
  { id: generateId(), date: '07 Feb 2026', description: 'Uber rides', category: 'Life Infrastructure', amount: 300, paymentMode: 'UPI', type: 'Need', notes: 'Mall trip' },
  { id: generateId(), date: '08 Feb 2026', description: 'Groceries - DMart', category: 'Life Infrastructure', amount: 1100, paymentMode: 'Cash', type: 'Need', notes: 'Weekly buy' },
  { id: generateId(), date: '08 Feb 2026', description: 'Brunch out', category: 'Lifestyle Enjoyment', amount: 600, paymentMode: 'UPI', type: 'Want', notes: 'Sunday brunch' },
  { id: generateId(), date: '08 Feb 2026', description: 'Laundry', category: 'Life Infrastructure', amount: 200, paymentMode: 'UPI', type: 'Need', notes: 'Dry cleaning' },
  { id: generateId(), date: '09 Feb 2026', description: 'Auto to metro', category: 'Life Infrastructure', amount: 40, paymentMode: 'Cash', type: 'Need', notes: 'Commute' },
  { id: generateId(), date: '09 Feb 2026', description: 'Swiggy lunch', category: 'Lifestyle Enjoyment', amount: 250, paymentMode: 'UPI', type: 'Want', notes: 'Chole bhature' },
  { id: generateId(), date: '09 Feb 2026', description: 'Chai tapri', category: 'Lifestyle Enjoyment', amount: 30, paymentMode: 'Cash', type: 'Want', notes: 'Evening chai' },
  { id: generateId(), date: '10 Feb 2026', description: 'Internet Bill', category: 'Life Infrastructure', amount: 799, paymentMode: 'UPI', type: 'Need', notes: 'Broadband' },
  { id: generateId(), date: '10 Feb 2026', description: 'Books - Amazon', category: 'Performance & Growth', amount: 350, paymentMode: 'UPI', type: 'Need', notes: 'Psychology of Money' },
  { id: generateId(), date: '10 Feb 2026', description: 'Uber', category: 'Life Infrastructure', amount: 170, paymentMode: 'UPI', type: 'Need', notes: 'Commute' },
  { id: generateId(), date: '11 Feb 2026', description: 'Groceries - Zepto', category: 'Life Infrastructure', amount: 290, paymentMode: 'UPI', type: 'Need', notes: 'Quick run' },
  { id: generateId(), date: '11 Feb 2026', description: 'Lunch treat for intern', category: 'Relationships & Generosity', amount: 400, paymentMode: 'UPI', type: 'Want', notes: 'Team bonding' },
  { id: generateId(), date: '12 Feb 2026', description: 'Swiggy dinner', category: 'Lifestyle Enjoyment', amount: 320, paymentMode: 'UPI', type: 'Want', notes: 'Thai food' },
  { id: generateId(), date: '12 Feb 2026', description: 'Medicine', category: 'Life Infrastructure', amount: 250, paymentMode: 'Cash', type: 'Need', notes: 'Vitamins' },
  { id: generateId(), date: '12 Feb 2026', description: 'Spotify', category: 'Lifestyle Enjoyment', amount: 119, paymentMode: 'Credit Card', type: 'Want', notes: 'Monthly sub' },
  { id: generateId(), date: '13 Feb 2026', description: 'Valentine gift - perfume', category: 'Relationships & Generosity', amount: 2200, paymentMode: 'Credit Card', type: 'Want', notes: 'Gift for partner' },
  { id: generateId(), date: '13 Feb 2026', description: 'Flowers', category: 'Relationships & Generosity', amount: 500, paymentMode: 'UPI', type: 'Want', notes: 'Roses' },
  { id: generateId(), date: '13 Feb 2026', description: 'Haircut', category: 'Lifestyle Enjoyment', amount: 300, paymentMode: 'Cash', type: 'Want', notes: 'Grooming' },
  { id: generateId(), date: '14 Feb 2026', description: 'Valentine dinner - fancy restaurant', category: 'Relationships & Generosity', amount: 3500, paymentMode: 'Credit Card', type: 'Want', notes: 'Date night' },
  { id: generateId(), date: '14 Feb 2026', description: 'Uber rides', category: 'Life Infrastructure', amount: 400, paymentMode: 'UPI', type: 'Need', notes: 'To and from restaurant' },
  { id: generateId(), date: '14 Feb 2026', description: 'Dessert', category: 'Lifestyle Enjoyment', amount: 350, paymentMode: 'UPI', type: 'Want', notes: 'Cake stop' },
  { id: generateId(), date: '15 Feb 2026', description: 'FD Deposit', category: 'Future Me', amount: 2000, paymentMode: 'Bank Transfer', type: 'Saving', notes: 'Quarterly FD - smaller this time' },
  { id: generateId(), date: '15 Feb 2026', description: 'Groceries - BigBasket', category: 'Life Infrastructure', amount: 850, paymentMode: 'UPI', type: 'Need', notes: 'Restock' },
  { id: generateId(), date: '15 Feb 2026', description: 'Swiggy dinner', category: 'Lifestyle Enjoyment', amount: 300, paymentMode: 'UPI', type: 'Want', notes: 'Lazy Sunday' },
  { id: generateId(), date: '16 Feb 2026', description: 'Water Bill', category: 'Life Infrastructure', amount: 200, paymentMode: 'UPI', type: 'Need', notes: 'Quarterly' },
  { id: generateId(), date: '16 Feb 2026', description: 'Chai + vada pav', category: 'Lifestyle Enjoyment', amount: 60, paymentMode: 'Cash', type: 'Want', notes: 'Snack' },
  { id: generateId(), date: '17 Feb 2026', description: 'Uber rides', category: 'Life Infrastructure', amount: 200, paymentMode: 'UPI', type: 'Need', notes: 'Commute' },
  { id: generateId(), date: '17 Feb 2026', description: 'Swiggy lunch', category: 'Lifestyle Enjoyment', amount: 270, paymentMode: 'UPI', type: 'Want', notes: 'Paneer tikka' },
  { id: generateId(), date: '18 Feb 2026', description: 'Groceries - Zepto', category: 'Life Infrastructure', amount: 350, paymentMode: 'UPI', type: 'Need', notes: 'Essentials' },
  { id: generateId(), date: '18 Feb 2026', description: 'Auto rides', category: 'Life Infrastructure', amount: 80, paymentMode: 'Cash', type: 'Need', notes: 'Short trips' },
  { id: generateId(), date: '19 Feb 2026', description: 'Team treat', category: 'Relationships & Generosity', amount: 600, paymentMode: 'UPI', type: 'Want', notes: 'Project ship' },
  { id: generateId(), date: '19 Feb 2026', description: 'Paan', category: 'Lifestyle Enjoyment', amount: 40, paymentMode: 'Cash', type: 'Want', notes: 'After dinner' },
  { id: generateId(), date: '20 Feb 2026', description: 'Petrol', category: 'Life Infrastructure', amount: 700, paymentMode: 'Debit Card', type: 'Need', notes: 'Bike fuel' },
  { id: generateId(), date: '20 Feb 2026', description: 'Dinner out', category: 'Lifestyle Enjoyment', amount: 800, paymentMode: 'Credit Card', type: 'Want', notes: 'Friday treat' },
  { id: generateId(), date: '21 Feb 2026', description: 'Cafe with friends', category: 'Lifestyle Enjoyment', amount: 400, paymentMode: 'UPI', type: 'Want', notes: 'Saturday chill' },
  { id: generateId(), date: '21 Feb 2026', description: 'Amazon - Phone charger', category: 'Life Infrastructure', amount: 500, paymentMode: 'Credit Card', type: 'Need', notes: 'Old one broke' },
  { id: generateId(), date: '22 Feb 2026', description: 'Groceries - DMart', category: 'Life Infrastructure', amount: 950, paymentMode: 'Cash', type: 'Need', notes: 'Weekly buy' },
  { id: generateId(), date: '22 Feb 2026', description: 'Cooking gas', category: 'Life Infrastructure', amount: 900, paymentMode: 'UPI', type: 'Need', notes: 'Cylinder refill' },
  { id: generateId(), date: '23 Feb 2026', description: 'Metro recharge', category: 'Life Infrastructure', amount: 200, paymentMode: 'UPI', type: 'Need', notes: 'Top up' },
  { id: generateId(), date: '23 Feb 2026', description: 'Coffee Starbucks', category: 'Lifestyle Enjoyment', amount: 350, paymentMode: 'UPI', type: 'Want', notes: 'Monday coffee' },
  { id: generateId(), date: '24 Feb 2026', description: 'Swiggy lunch', category: 'Lifestyle Enjoyment', amount: 240, paymentMode: 'UPI', type: 'Want', notes: 'Quick bite' },
  { id: generateId(), date: '24 Feb 2026', description: 'Uber', category: 'Life Infrastructure', amount: 160, paymentMode: 'UPI', type: 'Need', notes: 'Late meeting' },
  { id: generateId(), date: '25 Feb 2026', description: 'Groceries - Zepto', category: 'Life Infrastructure', amount: 280, paymentMode: 'UPI', type: 'Need', notes: 'Milk curd bread' },
  { id: generateId(), date: '25 Feb 2026', description: 'Chai tapri', category: 'Lifestyle Enjoyment', amount: 30, paymentMode: 'Cash', type: 'Want', notes: 'Chai break' },
  { id: generateId(), date: '26 Feb 2026', description: 'Drinks with old friends', category: 'Lifestyle Enjoyment', amount: 1200, paymentMode: 'Credit Card', type: 'Want', notes: 'Thursday night' },
  { id: generateId(), date: '26 Feb 2026', description: 'Uber late night', category: 'Life Infrastructure', amount: 320, paymentMode: 'UPI', type: 'Need', notes: 'Cab home' },
  { id: generateId(), date: '27 Feb 2026', description: 'Zomato dinner', category: 'Lifestyle Enjoyment', amount: 400, paymentMode: 'UPI', type: 'Want', notes: 'Friday order' },
  { id: generateId(), date: '27 Feb 2026', description: 'Parking', category: 'Life Infrastructure', amount: 50, paymentMode: 'Cash', type: 'Need', notes: 'Office parking' },
  { id: generateId(), date: '28 Feb 2026', description: 'Groceries', category: 'Life Infrastructure', amount: 600, paymentMode: 'UPI', type: 'Need', notes: 'Month end stock' },
  { id: generateId(), date: '28 Feb 2026', description: 'Swiggy dessert', category: 'Lifestyle Enjoyment', amount: 200, paymentMode: 'UPI', type: 'Want', notes: 'Cheesecake' },
  { id: generateId(), date: '28 Feb 2026', description: 'Auto', category: 'Life Infrastructure', amount: 50, paymentMode: 'Cash', type: 'Need', notes: 'Short ride' },

  // March 2026
  { id: generateId(), date: '01 Mar 2026', description: 'House Rent', category: 'Life Infrastructure', amount: 12000, paymentMode: 'Bank Transfer', type: 'Need', notes: 'Monthly rent' },
  { id: generateId(), date: '01 Mar 2026', description: 'Groceries - BigBasket', category: 'Life Infrastructure', amount: 1800, paymentMode: 'UPI', type: 'Need', notes: 'Monthly grocery stock' },
  { id: generateId(), date: '01 Mar 2026', description: 'Chai tapri', category: 'Lifestyle Enjoyment', amount: 30, paymentMode: 'Cash', type: 'Want', notes: 'Morning chai' },
  { id: generateId(), date: '01 Mar 2026', description: 'Swiggy lunch', category: 'Lifestyle Enjoyment', amount: 280, paymentMode: 'UPI', type: 'Want', notes: 'Biryani' },
  { id: generateId(), date: '02 Mar 2026', description: 'Metro Card Recharge', category: 'Life Infrastructure', amount: 500, paymentMode: 'UPI', type: 'Need', notes: 'Monthly commute' },
  { id: generateId(), date: '02 Mar 2026', description: 'Mobile Recharge', category: 'Life Infrastructure', amount: 299, paymentMode: 'UPI', type: 'Need', notes: 'Airtel plan' },
  { id: generateId(), date: '02 Mar 2026', description: 'Chai + samosa', category: 'Lifestyle Enjoyment', amount: 50, paymentMode: 'Cash', type: 'Want', notes: 'Office break' },
  { id: generateId(), date: '03 Mar 2026', description: 'Gym Membership', category: 'Performance & Growth', amount: 1500, paymentMode: 'Debit Card', type: 'Need', notes: 'Monthly gym' },
  { id: generateId(), date: '03 Mar 2026', description: 'Uber to office', category: 'Life Infrastructure', amount: 180, paymentMode: 'UPI', type: 'Need', notes: 'Late for meeting' },
  { id: generateId(), date: '03 Mar 2026', description: 'Zepto snacks', category: 'Life Infrastructure', amount: 320, paymentMode: 'UPI', type: 'Need', notes: 'Chips, biscuits, juice' },
  { id: generateId(), date: '04 Mar 2026', description: 'Netflix Subscription', category: 'Lifestyle Enjoyment', amount: 199, paymentMode: 'Credit Card', type: 'Want', notes: 'Monthly sub' },
  { id: generateId(), date: '04 Mar 2026', description: 'Lunch canteen', category: 'Lifestyle Enjoyment', amount: 120, paymentMode: 'Cash', type: 'Want', notes: 'Office lunch' },
  { id: generateId(), date: '04 Mar 2026', description: 'Auto rickshaw', category: 'Life Infrastructure', amount: 60, paymentMode: 'Cash', type: 'Need', notes: 'Metro to office' },
  { id: generateId(), date: '05 Mar 2026', description: 'Dinner with friends', category: 'Relationships & Generosity', amount: 1200, paymentMode: 'UPI', type: 'Want', notes: 'Birthday dinner for Rahul' },
  { id: generateId(), date: '05 Mar 2026', description: 'Uber back home', category: 'Life Infrastructure', amount: 220, paymentMode: 'UPI', type: 'Need', notes: 'Late night cab' },
  { id: generateId(), date: '05 Mar 2026', description: 'Tea + biscuits', category: 'Lifestyle Enjoyment', amount: 40, paymentMode: 'Cash', type: 'Want', notes: 'Evening snack' },
  { id: generateId(), date: '06 Mar 2026', description: 'Groceries - Zepto', category: 'Life Infrastructure', amount: 650, paymentMode: 'UPI', type: 'Need', notes: 'Fruits and veggies' },
  { id: generateId(), date: '06 Mar 2026', description: 'Petrol', category: 'Life Infrastructure', amount: 800, paymentMode: 'Debit Card', type: 'Need', notes: 'Bike fuel' },
  { id: generateId(), date: '06 Mar 2026', description: 'Swiggy dinner', category: 'Lifestyle Enjoyment', amount: 450, paymentMode: 'UPI', type: 'Want', notes: 'Pizza night' },
  { id: generateId(), date: '07 Mar 2026', description: 'SIP - Mutual Fund', category: 'Future Me', amount: 5000, paymentMode: 'Bank Transfer', type: 'Saving', notes: 'Monthly SIP' },
  { id: generateId(), date: '07 Mar 2026', description: 'Movie tickets', category: 'Lifestyle Enjoyment', amount: 600, paymentMode: 'UPI', type: 'Want', notes: 'Weekend movie' },
  { id: generateId(), date: '07 Mar 2026', description: 'Popcorn + drinks', category: 'Lifestyle Enjoyment', amount: 350, paymentMode: 'Cash', type: 'Want', notes: 'At the theater' },
  { id: generateId(), date: '07 Mar 2026', description: 'Zomato dinner', category: 'Lifestyle Enjoyment', amount: 550, paymentMode: 'UPI', type: 'Want', notes: 'Post movie dinner' },
  { id: generateId(), date: '07 Mar 2026', description: 'Uber rides', category: 'Life Infrastructure', amount: 300, paymentMode: 'UPI', type: 'Need', notes: 'To and from mall' },
  { id: generateId(), date: '08 Mar 2026', description: 'Electricity Bill', category: 'Life Infrastructure', amount: 1400, paymentMode: 'UPI', type: 'Need', notes: 'March bill' },
  { id: generateId(), date: '08 Mar 2026', description: 'Brunch out', category: 'Lifestyle Enjoyment', amount: 750, paymentMode: 'Credit Card', type: 'Want', notes: 'Sunday brunch' },
  { id: generateId(), date: '08 Mar 2026', description: 'Groceries - DMart', category: 'Life Infrastructure', amount: 1200, paymentMode: 'Cash', type: 'Need', notes: 'Weekly bulk buy' },
  { id: generateId(), date: '09 Mar 2026', description: 'Coffee - Starbucks', category: 'Lifestyle Enjoyment', amount: 350, paymentMode: 'UPI', type: 'Want', notes: 'Monday motivation' },
  { id: generateId(), date: '09 Mar 2026', description: 'Auto to metro', category: 'Life Infrastructure', amount: 40, paymentMode: 'Cash', type: 'Need', notes: 'Commute' },
  { id: generateId(), date: '10 Mar 2026', description: 'Uber rides', category: 'Life Infrastructure', amount: 190, paymentMode: 'UPI', type: 'Need', notes: 'Rain day cab' },
  { id: generateId(), date: '10 Mar 2026', description: 'Online Course - Udemy', category: 'Performance & Growth', amount: 499, paymentMode: 'Credit Card', type: 'Need', notes: 'Python course' },
  { id: generateId(), date: '10 Mar 2026', description: 'Chai tapri', category: 'Lifestyle Enjoyment', amount: 30, paymentMode: 'Cash', type: 'Want', notes: 'Evening chai' },
  { id: generateId(), date: '11 Mar 2026', description: 'Lunch with colleague', category: 'Relationships & Generosity', amount: 400, paymentMode: 'UPI', type: 'Want', notes: 'Team lunch' },
  { id: generateId(), date: '11 Mar 2026', description: 'Amazon - Phone case', category: 'Lifestyle Enjoyment', amount: 299, paymentMode: 'Credit Card', type: 'Want', notes: 'New case' },
  { id: generateId(), date: '12 Mar 2026', description: 'Groceries - Zepto', category: 'Life Infrastructure', amount: 480, paymentMode: 'UPI', type: 'Need', notes: 'Milk, bread, eggs' },
  { id: generateId(), date: '12 Mar 2026', description: 'Swiggy lunch', category: 'Lifestyle Enjoyment', amount: 200, paymentMode: 'UPI', type: 'Want', notes: 'Office lunch' },
  { id: generateId(), date: '12 Mar 2026', description: 'Medicine', category: 'Life Infrastructure', amount: 350, paymentMode: 'Cash', type: 'Need', notes: 'Cold medicine' },
  { id: generateId(), date: '13 Mar 2026', description: 'Drinks with friends', category: 'Relationships & Generosity', amount: 1500, paymentMode: 'Credit Card', type: 'Want', notes: 'Friday night out' },
  { id: generateId(), date: '13 Mar 2026', description: 'Uber late night', category: 'Life Infrastructure', amount: 350, paymentMode: 'UPI', type: 'Need', notes: 'Cab home' },
  { id: generateId(), date: '13 Mar 2026', description: 'Street food', category: 'Lifestyle Enjoyment', amount: 150, paymentMode: 'Cash', type: 'Want', notes: 'Momos + golgappa' },
  { id: generateId(), date: '14 Mar 2026', description: 'Gift for mom', category: 'Relationships & Generosity', amount: 2000, paymentMode: 'Debit Card', type: 'Want', notes: 'Birthday gift' },
  { id: generateId(), date: '14 Mar 2026', description: 'Cake', category: 'Relationships & Generosity', amount: 600, paymentMode: 'UPI', type: 'Want', notes: 'Birthday cake' },
  { id: generateId(), date: '14 Mar 2026', description: 'Family dinner out', category: 'Relationships & Generosity', amount: 2500, paymentMode: 'Credit Card', type: 'Want', notes: 'Mom birthday dinner' },
  { id: generateId(), date: '14 Mar 2026', description: 'Uber rides', category: 'Life Infrastructure', amount: 250, paymentMode: 'UPI', type: 'Need', notes: 'To restaurant and back' },
  { id: generateId(), date: '15 Mar 2026', description: 'FD Deposit', category: 'Future Me', amount: 3000, paymentMode: 'Bank Transfer', type: 'Saving', notes: 'Quarterly FD' },
  { id: generateId(), date: '15 Mar 2026', description: 'Groceries - BigBasket', category: 'Life Infrastructure', amount: 950, paymentMode: 'UPI', type: 'Need', notes: 'Weekly restock' },
  { id: generateId(), date: '15 Mar 2026', description: 'Laundry', category: 'Life Infrastructure', amount: 200, paymentMode: 'UPI', type: 'Need', notes: 'Dry cleaning' },
  { id: generateId(), date: '16 Mar 2026', description: 'Water Bill', category: 'Life Infrastructure', amount: 200, paymentMode: 'UPI', type: 'Need', notes: 'Quarterly' },
  { id: generateId(), date: '16 Mar 2026', description: 'Chai + vada pav', category: 'Lifestyle Enjoyment', amount: 60, paymentMode: 'Cash', type: 'Want', notes: 'Lunch snack' },
  { id: generateId(), date: '16 Mar 2026', description: 'Metro recharge', category: 'Life Infrastructure', amount: 200, paymentMode: 'UPI', type: 'Need', notes: 'Top up' },
  { id: generateId(), date: '17 Mar 2026', description: 'Swiggy orders', category: 'Lifestyle Enjoyment', amount: 380, paymentMode: 'Credit Card', type: 'Want', notes: 'Lunch delivery' },
  { id: generateId(), date: '17 Mar 2026', description: 'Books - Flipkart', category: 'Performance & Growth', amount: 450, paymentMode: 'UPI', type: 'Need', notes: 'Atomic Habits' },
  { id: generateId(), date: '18 Mar 2026', description: 'Haircut', category: 'Lifestyle Enjoyment', amount: 300, paymentMode: 'Cash', type: 'Want', notes: 'Monthly trim' },
  { id: generateId(), date: '18 Mar 2026', description: 'Groceries - Zepto', category: 'Life Infrastructure', amount: 290, paymentMode: 'UPI', type: 'Need', notes: 'Quick essentials' },
  { id: generateId(), date: '18 Mar 2026', description: 'Chai tapri', category: 'Lifestyle Enjoyment', amount: 30, paymentMode: 'Cash', type: 'Want', notes: 'Chai break' },
  { id: generateId(), date: '19 Mar 2026', description: 'Amazon - Headphones', category: 'Lifestyle Enjoyment', amount: 1500, paymentMode: 'Credit Card', type: 'Want', notes: 'Replacement buds' },
  { id: generateId(), date: '19 Mar 2026', description: 'Lunch - office canteen', category: 'Lifestyle Enjoyment', amount: 110, paymentMode: 'Cash', type: 'Want', notes: 'Thali' },
  { id: generateId(), date: '20 Mar 2026', description: 'Petrol', category: 'Life Infrastructure', amount: 700, paymentMode: 'Debit Card', type: 'Need', notes: 'Bike fuel' },
  { id: generateId(), date: '20 Mar 2026', description: 'Dinner out', category: 'Lifestyle Enjoyment', amount: 900, paymentMode: 'Credit Card', type: 'Want', notes: 'Friday treat' },
  { id: generateId(), date: '20 Mar 2026', description: 'Parking', category: 'Life Infrastructure', amount: 50, paymentMode: 'Cash', type: 'Need', notes: 'Mall parking' },
  { id: generateId(), date: '20 Mar 2026', description: 'Ice cream', category: 'Lifestyle Enjoyment', amount: 150, paymentMode: 'UPI', type: 'Want', notes: 'Baskin Robbins' },
  { id: generateId(), date: '21 Mar 2026', description: 'Charity donation', category: 'Relationships & Generosity', amount: 500, paymentMode: 'UPI', type: 'Want', notes: 'Monthly donation' },
  { id: generateId(), date: '21 Mar 2026', description: 'Shopping - clothes', category: 'Lifestyle Enjoyment', amount: 2200, paymentMode: 'Credit Card', type: 'Want', notes: 'New shirt + jeans' },
  { id: generateId(), date: '21 Mar 2026', description: 'Cafe with friends', category: 'Lifestyle Enjoyment', amount: 450, paymentMode: 'UPI', type: 'Want', notes: 'Third Wave Coffee' },
  { id: generateId(), date: '21 Mar 2026', description: 'Auto rides', category: 'Life Infrastructure', amount: 120, paymentMode: 'Cash', type: 'Need', notes: 'Market trip' },
  { id: generateId(), date: '22 Mar 2026', description: 'PPF Contribution', category: 'Future Me', amount: 2000, paymentMode: 'Bank Transfer', type: 'Saving', notes: 'Monthly PPF' },
  { id: generateId(), date: '22 Mar 2026', description: 'Groceries - DMart', category: 'Life Infrastructure', amount: 1100, paymentMode: 'Cash', type: 'Need', notes: 'Weekly buy' },
  { id: generateId(), date: '22 Mar 2026', description: 'Swiggy dinner', category: 'Lifestyle Enjoyment', amount: 320, paymentMode: 'UPI', type: 'Want', notes: 'Lazy Sunday dinner' },
  { id: generateId(), date: '23 Mar 2026', description: 'Uber to office', category: 'Life Infrastructure', amount: 200, paymentMode: 'UPI', type: 'Need', notes: 'Running late' },
  { id: generateId(), date: '23 Mar 2026', description: 'Chai + sandwich', category: 'Lifestyle Enjoyment', amount: 80, paymentMode: 'Cash', type: 'Want', notes: 'Evening snack' },
  { id: generateId(), date: '24 Mar 2026', description: 'Internet Bill', category: 'Life Infrastructure', amount: 799, paymentMode: 'UPI', type: 'Need', notes: 'Broadband monthly' },
  { id: generateId(), date: '24 Mar 2026', description: 'Zepto groceries', category: 'Life Infrastructure', amount: 350, paymentMode: 'UPI', type: 'Need', notes: 'Milk, curd, bread' },
  { id: generateId(), date: '24 Mar 2026', description: 'Swiggy lunch', category: 'Lifestyle Enjoyment', amount: 250, paymentMode: 'UPI', type: 'Want', notes: 'Butter chicken' },
  { id: generateId(), date: '25 Mar 2026', description: 'Spotify', category: 'Lifestyle Enjoyment', amount: 119, paymentMode: 'Credit Card', type: 'Want', notes: 'Monthly sub' },
  { id: generateId(), date: '25 Mar 2026', description: 'Auto + metro', category: 'Life Infrastructure', amount: 80, paymentMode: 'Cash', type: 'Need', notes: 'Commute' },
  { id: generateId(), date: '26 Mar 2026', description: 'Team treat', category: 'Relationships & Generosity', amount: 800, paymentMode: 'UPI', type: 'Want', notes: 'Project completion' },
  { id: generateId(), date: '26 Mar 2026', description: 'Uber home', category: 'Life Infrastructure', amount: 170, paymentMode: 'UPI', type: 'Need', notes: 'Late evening' },
  { id: generateId(), date: '26 Mar 2026', description: 'Paan', category: 'Lifestyle Enjoyment', amount: 40, paymentMode: 'Cash', type: 'Want', notes: 'After dinner' },
  { id: generateId(), date: '27 Mar 2026', description: 'Dinner out', category: 'Lifestyle Enjoyment', amount: 1100, paymentMode: 'Credit Card', type: 'Want', notes: 'Korean BBQ' },
  { id: generateId(), date: '27 Mar 2026', description: 'Dessert', category: 'Lifestyle Enjoyment', amount: 300, paymentMode: 'UPI', type: 'Want', notes: 'Theobroma' },
  { id: generateId(), date: '27 Mar 2026', description: 'Uber rides', category: 'Life Infrastructure', amount: 280, paymentMode: 'UPI', type: 'Need', notes: 'Friday night cab' },
  { id: generateId(), date: '28 Mar 2026', description: 'Groceries - BigBasket', category: 'Life Infrastructure', amount: 1400, paymentMode: 'UPI', type: 'Need', notes: 'Monthly restock big' },
  { id: generateId(), date: '28 Mar 2026', description: 'Salon', category: 'Lifestyle Enjoyment', amount: 500, paymentMode: 'Cash', type: 'Want', notes: 'Facial + cleanup' },
  { id: generateId(), date: '28 Mar 2026', description: 'Zomato brunch', category: 'Lifestyle Enjoyment', amount: 650, paymentMode: 'UPI', type: 'Want', notes: 'Weekend brunch order' },
  { id: generateId(), date: '28 Mar 2026', description: 'Petrol', category: 'Life Infrastructure', amount: 500, paymentMode: 'Debit Card', type: 'Need', notes: 'Bike top up' },
  { id: generateId(), date: '29 Mar 2026', description: 'Cooking gas', category: 'Life Infrastructure', amount: 900, paymentMode: 'UPI', type: 'Need', notes: 'Cylinder refill' },
  { id: generateId(), date: '29 Mar 2026', description: 'Groceries - Zepto', category: 'Life Infrastructure', amount: 250, paymentMode: 'UPI', type: 'Need', notes: 'Quick needs' },
  { id: generateId(), date: '29 Mar 2026', description: 'Street food outing', category: 'Lifestyle Enjoyment', amount: 350, paymentMode: 'Cash', type: 'Want', notes: 'Chaat + kulfi' },
  { id: generateId(), date: '30 Mar 2026', description: 'Medicine refill', category: 'Life Infrastructure', amount: 450, paymentMode: 'Cash', type: 'Need', notes: 'Monthly meds' },
  { id: generateId(), date: '30 Mar 2026', description: 'Uber', category: 'Life Infrastructure', amount: 150, paymentMode: 'UPI', type: 'Need', notes: 'Commute' },
  { id: generateId(), date: '30 Mar 2026', description: 'Chai tapri', category: 'Lifestyle Enjoyment', amount: 30, paymentMode: 'Cash', type: 'Want', notes: 'Morning chai' },
  { id: generateId(), date: '31 Mar 2026', description: 'Electricity deposit', category: 'Life Infrastructure', amount: 500, paymentMode: 'UPI', type: 'Need', notes: 'Security deposit' },
  { id: generateId(), date: '31 Mar 2026', description: 'Swiggy dinner', category: 'Lifestyle Enjoyment', amount: 380, paymentMode: 'UPI', type: 'Want', notes: 'Month end treat' },
  { id: generateId(), date: '31 Mar 2026', description: 'Auto', category: 'Life Infrastructure', amount: 50, paymentMode: 'Cash', type: 'Need', notes: 'Short ride' },

  // April 2026
  { id: generateId(), date: '01 Apr 2026', description: 'House Rent', category: 'Life Infrastructure', amount: 12000, paymentMode: 'Bank Transfer', type: 'Need', notes: 'Monthly rent' },
  { id: generateId(), date: '01 Apr 2026', description: 'Groceries - BigBasket', category: 'Life Infrastructure', amount: 1700, paymentMode: 'UPI', type: 'Need', notes: 'Monthly stock' },
  { id: generateId(), date: '01 Apr 2026', description: 'Chai tapri', category: 'Lifestyle Enjoyment', amount: 30, paymentMode: 'Cash', type: 'Want', notes: 'Morning chai' },
  { id: generateId(), date: '01 Apr 2026', description: 'Canteen lunch', category: 'Lifestyle Enjoyment', amount: 120, paymentMode: 'Cash', type: 'Want', notes: 'Office' },
  { id: generateId(), date: '02 Apr 2026', description: 'Metro Card Recharge', category: 'Life Infrastructure', amount: 500, paymentMode: 'UPI', type: 'Need', notes: 'Monthly pass' },
  { id: generateId(), date: '02 Apr 2026', description: 'Mobile Recharge', category: 'Life Infrastructure', amount: 299, paymentMode: 'UPI', type: 'Need', notes: 'Airtel plan' },
  { id: generateId(), date: '02 Apr 2026', description: 'Swiggy dinner', category: 'Lifestyle Enjoyment', amount: 280, paymentMode: 'UPI', type: 'Want', notes: 'Quick dinner' },
  { id: generateId(), date: '03 Apr 2026', description: 'Gym Membership', category: 'Performance & Growth', amount: 1500, paymentMode: 'Debit Card', type: 'Need', notes: 'Monthly gym' },
  { id: generateId(), date: '03 Apr 2026', description: 'Coffee - Third Wave', category: 'Lifestyle Enjoyment', amount: 280, paymentMode: 'UPI', type: 'Want', notes: 'Friday coffee' },
  { id: generateId(), date: '03 Apr 2026', description: 'Zomato dinner', category: 'Lifestyle Enjoyment', amount: 400, paymentMode: 'UPI', type: 'Want', notes: 'Friday night' },
  { id: generateId(), date: '04 Apr 2026', description: 'SIP - Mutual Fund', category: 'Future Me', amount: 5000, paymentMode: 'Bank Transfer', type: 'Saving', notes: 'Monthly SIP on time' },
  { id: generateId(), date: '04 Apr 2026', description: 'Groceries - DMart', category: 'Life Infrastructure', amount: 1100, paymentMode: 'Cash', type: 'Need', notes: 'Weekly buy' },
  { id: generateId(), date: '04 Apr 2026', description: 'Cafe with friends', category: 'Lifestyle Enjoyment', amount: 380, paymentMode: 'UPI', type: 'Want', notes: 'Saturday hangout' },
  { id: generateId(), date: '04 Apr 2026', description: 'Auto rides', category: 'Life Infrastructure', amount: 100, paymentMode: 'Cash', type: 'Need', notes: 'Market trip' },
  { id: generateId(), date: '05 Apr 2026', description: 'Netflix', category: 'Lifestyle Enjoyment', amount: 199, paymentMode: 'Credit Card', type: 'Want', notes: 'Monthly sub' },
  { id: generateId(), date: '05 Apr 2026', description: 'Spotify', category: 'Lifestyle Enjoyment', amount: 119, paymentMode: 'Credit Card', type: 'Want', notes: 'Monthly sub' },
  { id: generateId(), date: '05 Apr 2026', description: 'Swiggy lunch', category: 'Lifestyle Enjoyment', amount: 250, paymentMode: 'UPI', type: 'Want', notes: 'Lazy Sunday' },
  { id: generateId(), date: '05 Apr 2026', description: 'Laundry', category: 'Life Infrastructure', amount: 200, paymentMode: 'UPI', type: 'Need', notes: 'Dry cleaning' },
  { id: generateId(), date: '06 Apr 2026', description: 'Electricity Bill', category: 'Life Infrastructure', amount: 1350, paymentMode: 'UPI', type: 'Need', notes: 'April bill' },
  { id: generateId(), date: '06 Apr 2026', description: 'Uber to office', category: 'Life Infrastructure', amount: 180, paymentMode: 'UPI', type: 'Need', notes: 'Monday rush' },
  { id: generateId(), date: '06 Apr 2026', description: 'Chai + samosa', category: 'Lifestyle Enjoyment', amount: 50, paymentMode: 'Cash', type: 'Want', notes: 'Break time' },
  { id: generateId(), date: '07 Apr 2026', description: 'Petrol', category: 'Life Infrastructure', amount: 750, paymentMode: 'Debit Card', type: 'Need', notes: 'Bike fuel' },
  { id: generateId(), date: '07 Apr 2026', description: 'Groceries - Zepto', category: 'Life Infrastructure', amount: 380, paymentMode: 'UPI', type: 'Need', notes: 'Fruits veggies' },
  { id: generateId(), date: '07 Apr 2026', description: 'Canteen lunch', category: 'Lifestyle Enjoyment', amount: 130, paymentMode: 'Cash', type: 'Want', notes: 'Thali' },
  { id: generateId(), date: '08 Apr 2026', description: 'Internet Bill', category: 'Life Infrastructure', amount: 799, paymentMode: 'UPI', type: 'Need', notes: 'Broadband' },
  { id: generateId(), date: '08 Apr 2026', description: 'Dinner with colleague', category: 'Relationships & Generosity', amount: 500, paymentMode: 'UPI', type: 'Want', notes: 'Farewell dinner' },
  { id: generateId(), date: '08 Apr 2026', description: 'Chai tapri', category: 'Lifestyle Enjoyment', amount: 30, paymentMode: 'Cash', type: 'Want', notes: 'Evening chai' },
  { id: generateId(), date: '09 Apr 2026', description: 'Uber rides', category: 'Life Infrastructure', amount: 200, paymentMode: 'UPI', type: 'Need', notes: 'Commute' },
  { id: generateId(), date: '09 Apr 2026', description: 'Swiggy lunch', category: 'Lifestyle Enjoyment', amount: 220, paymentMode: 'UPI', type: 'Want', notes: 'Office order' },
  { id: generateId(), date: '10 Apr 2026', description: 'PPF Contribution', category: 'Future Me', amount: 2000, paymentMode: 'Bank Transfer', type: 'Saving', notes: 'Monthly PPF' },
  { id: generateId(), date: '10 Apr 2026', description: 'Dinner out', category: 'Lifestyle Enjoyment', amount: 750, paymentMode: 'Credit Card', type: 'Want', notes: 'Friday dinner' },
  { id: generateId(), date: '10 Apr 2026', description: 'Uber', category: 'Life Infrastructure', amount: 250, paymentMode: 'UPI', type: 'Need', notes: 'Cab home' },
  { id: generateId(), date: '11 Apr 2026', description: 'Groceries - BigBasket', category: 'Life Infrastructure', amount: 900, paymentMode: 'UPI', type: 'Need', notes: 'Restock' },
  { id: generateId(), date: '11 Apr 2026', description: 'Movie + snacks', category: 'Lifestyle Enjoyment', amount: 700, paymentMode: 'UPI', type: 'Want', notes: 'Weekend movie' },
  { id: generateId(), date: '11 Apr 2026', description: 'Zomato dinner', category: 'Lifestyle Enjoyment', amount: 450, paymentMode: 'UPI', type: 'Want', notes: 'Post movie food' },
  { id: generateId(), date: '11 Apr 2026', description: 'Uber rides', category: 'Life Infrastructure', amount: 280, paymentMode: 'UPI', type: 'Need', notes: 'Mall trip' },
  { id: generateId(), date: '12 Apr 2026', description: 'FD Deposit', category: 'Future Me', amount: 3000, paymentMode: 'Bank Transfer', type: 'Saving', notes: 'Quarterly FD' },
  { id: generateId(), date: '12 Apr 2026', description: 'Brunch out', category: 'Lifestyle Enjoyment', amount: 600, paymentMode: 'UPI', type: 'Want', notes: 'Sunday brunch' },
  { id: generateId(), date: '12 Apr 2026', description: 'Groceries - Zepto', category: 'Life Infrastructure', amount: 300, paymentMode: 'UPI', type: 'Need', notes: 'Quick essentials' },
  { id: generateId(), date: '12 Apr 2026', description: 'Chai tapri', category: 'Lifestyle Enjoyment', amount: 30, paymentMode: 'Cash', type: 'Want', notes: 'Evening chai' },
];

export async function loadTransactions(): Promise<Transaction[]> {
  try {
    const data = await AsyncStorage.getItem(STORAGE_KEY);
    if (data) {
      const parsed = JSON.parse(data);
      if (Array.isArray(parsed) && parsed.length > 0) return parsed;
    }
    // Pre-load sample data
    await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(SAMPLE_TRANSACTIONS));
    return SAMPLE_TRANSACTIONS;
  } catch {
    return SAMPLE_TRANSACTIONS;
  }
}

export async function saveTransactions(transactions: Transaction[]): Promise<void> {
  await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(transactions));
}

export function createTransaction(
  data: Omit<Transaction, 'id'>
): Transaction {
  return { ...data, id: generateId() };
}
