import AsyncStorage from '@react-native-async-storage/async-storage';
import { Transaction, CATEGORY_TYPE_MAP } from '@/constants/config';

const STORAGE_KEY = 'finance_transactions';
const STORAGE_VERSION_KEY = 'finance_data_version';
const CURRENT_VERSION = 'v5_may2026_accountlinked'; // bump this to force reload with new data

function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2);
}

function tx(
  date: string,
  description: string,
  category: Transaction['category'],
  amount: number,
  paymentMode: Transaction['paymentMode'],
  type: Transaction['type'],
  notes: string = '',
): Transaction {
  return { id: generateId(), date, description, category, amount, paymentMode, type, notes };
}

// ── Full sample data: Jan–May 2026 ────────────────────────────────────────
const SAMPLE_TRANSACTIONS: Transaction[] = [
  // ── January 2026 ─────────────────────────────────────────────────────
  tx('01 Jan 2026', 'Uber late night - NYE', 'Life Infrastructure', 450, 'UPI', 'Need', 'NYE cab home'),
  tx('01 Jan 2026', 'Brunch out with friends', 'Lifestyle Enjoyment', 950, 'Credit Card', 'Want', 'New year brunch'),
  tx('01 Jan 2026', 'Swiggy dinner', 'Lifestyle Enjoyment', 380, 'UPI', 'Want', 'Too tired to cook'),
  tx('02 Jan 2026', 'House Rent', 'Life Infrastructure', 12000, 'Bank Transfer', 'Need', 'Monthly rent'),
  tx('02 Jan 2026', 'Groceries - BigBasket', 'Life Infrastructure', 1600, 'UPI', 'Need', 'Monthly stock'),
  tx('02 Jan 2026', 'Swiggy lunch', 'Lifestyle Enjoyment', 320, 'UPI', 'Want', 'Office lunch'),
  tx('02 Jan 2026', 'Chai tapri', 'Lifestyle Enjoyment', 30, 'Cash', 'Want', 'Evening chai'),
  tx('03 Jan 2026', 'Myntra sale - clothes', 'Lifestyle Enjoyment', 3200, 'Credit Card', 'Want', 'New year sale haul'),
  tx('03 Jan 2026', 'Movie + popcorn', 'Lifestyle Enjoyment', 800, 'UPI', 'Want', 'Weekend movie'),
  tx('03 Jan 2026', 'Dinner out - Barbeque Nation', 'Lifestyle Enjoyment', 1100, 'Credit Card', 'Want', 'Saturday dinner'),
  tx('03 Jan 2026', 'Uber rides', 'Life Infrastructure', 280, 'UPI', 'Need', 'Mall + movie'),
  tx('04 Jan 2026', 'Zomato brunch', 'Lifestyle Enjoyment', 550, 'UPI', 'Want', 'Lazy Sunday'),
  tx('04 Jan 2026', 'Groceries - Zepto', 'Life Infrastructure', 420, 'UPI', 'Need', 'Quick essentials'),
  tx('04 Jan 2026', 'Amazon - Bluetooth speaker', 'Lifestyle Enjoyment', 1800, 'Credit Card', 'Want', 'Impulse buy'),
  tx('05 Jan 2026', 'Metro Card Recharge', 'Life Infrastructure', 500, 'UPI', 'Need', 'Monthly commute'),
  tx('05 Jan 2026', 'Mobile Recharge', 'Life Infrastructure', 299, 'UPI', 'Need', 'Airtel plan'),
  tx('05 Jan 2026', 'Coffee - Starbucks', 'Lifestyle Enjoyment', 380, 'UPI', 'Want', 'Monday blues'),
  tx('05 Jan 2026', 'Swiggy dinner', 'Lifestyle Enjoyment', 290, 'UPI', 'Want', 'Tired after work'),
  tx('06 Jan 2026', 'Gym Membership', 'Performance & Growth', 1500, 'Debit Card', 'Need', 'Monthly gym'),
  tx('06 Jan 2026', 'Uber to office', 'Life Infrastructure', 200, 'UPI', 'Need', 'Running late'),
  tx('06 Jan 2026', 'Lunch canteen', 'Lifestyle Enjoyment', 130, 'Cash', 'Want', 'Office lunch'),
  tx('07 Jan 2026', 'Netflix', 'Lifestyle Enjoyment', 199, 'Credit Card', 'Want', 'Monthly sub'),
  tx('07 Jan 2026', 'Spotify', 'Lifestyle Enjoyment', 119, 'Credit Card', 'Want', 'Monthly sub'),
  tx('07 Jan 2026', 'Zepto snacks', 'Life Infrastructure', 350, 'UPI', 'Need', 'Chips, drinks'),
  tx('07 Jan 2026', 'Auto rickshaw', 'Life Infrastructure', 60, 'Cash', 'Need', 'Short ride'),
  tx('08 Jan 2026', 'Electricity Bill', 'Life Infrastructure', 1400, 'UPI', 'Need', 'Jan bill'),
  tx('08 Jan 2026', 'Drinks with friends', 'Lifestyle Enjoyment', 1600, 'Credit Card', 'Want', 'Thursday night out'),
  tx('08 Jan 2026', 'Uber late night', 'Life Infrastructure', 350, 'UPI', 'Need', 'Cab home'),
  tx('09 Jan 2026', 'Petrol', 'Life Infrastructure', 800, 'Debit Card', 'Need', 'Bike fuel'),
  tx('09 Jan 2026', 'Pizza Hut dinner', 'Lifestyle Enjoyment', 650, 'UPI', 'Want', 'TGIF'),
  tx('09 Jan 2026', 'Chai + samosa', 'Lifestyle Enjoyment', 50, 'Cash', 'Want', 'Office snack'),
  tx('10 Jan 2026', 'Shopping - Nike shoes', 'Lifestyle Enjoyment', 4500, 'Credit Card', 'Want', 'New kicks'),
  tx('10 Jan 2026', 'Zomato dinner', 'Lifestyle Enjoyment', 700, 'UPI', 'Want', 'Korean food'),
  tx('10 Jan 2026', 'Uber rides', 'Life Infrastructure', 300, 'UPI', 'Need', 'Shopping trip'),
  tx('11 Jan 2026', 'Groceries - DMart', 'Life Infrastructure', 1100, 'Cash', 'Need', 'Weekly buy'),
  tx('11 Jan 2026', 'Swiggy lunch', 'Lifestyle Enjoyment', 280, 'UPI', 'Want', 'Lazy day'),
  tx('11 Jan 2026', 'Ice cream', 'Lifestyle Enjoyment', 200, 'UPI', 'Want', 'Baskin Robbins'),
  tx('12 Jan 2026', 'Uber to office', 'Life Infrastructure', 180, 'UPI', 'Need', 'Late again'),
  tx('12 Jan 2026', 'Lunch with colleague', 'Relationships & Generosity', 450, 'UPI', 'Want', 'Treat lunch'),
  tx('13 Jan 2026', 'Internet Bill', 'Life Infrastructure', 799, 'UPI', 'Need', 'Broadband'),
  tx('13 Jan 2026', 'Chai tapri', 'Lifestyle Enjoyment', 30, 'Cash', 'Want', 'Morning chai'),
  tx('13 Jan 2026', 'Swiggy dinner', 'Lifestyle Enjoyment', 350, 'UPI', 'Want', 'Butter chicken'),
  tx('14 Jan 2026', 'Water Bill', 'Life Infrastructure', 200, 'UPI', 'Need', 'Quarterly'),
  tx('14 Jan 2026', 'Amazon - Gaming mouse', 'Lifestyle Enjoyment', 900, 'Credit Card', 'Want', 'Impulse'),
  tx('14 Jan 2026', 'Street food', 'Lifestyle Enjoyment', 120, 'Cash', 'Want', 'Pani puri'),
  tx('15 Jan 2026', 'SIP - Mutual Fund', 'Future Me', 2000, 'Bank Transfer', 'Saving', 'Skipped last 2 months'),
  tx('15 Jan 2026', 'Groceries - Zepto', 'Life Infrastructure', 380, 'UPI', 'Need', 'Milk bread eggs'),
  tx('15 Jan 2026', 'Dinner out', 'Lifestyle Enjoyment', 800, 'Credit Card', 'Want', 'Midweek treat'),
  tx('16 Jan 2026', 'Uber rides', 'Life Infrastructure', 220, 'UPI', 'Need', 'Commute'),
  tx('16 Jan 2026', 'Drinks + karaoke', 'Lifestyle Enjoyment', 1400, 'Credit Card', 'Want', 'Friday night'),
  tx('17 Jan 2026', 'Brunch cafe', 'Lifestyle Enjoyment', 750, 'UPI', 'Want', 'Weekend brunch'),
  tx('17 Jan 2026', 'Flipkart - Earbuds', 'Lifestyle Enjoyment', 1200, 'Credit Card', 'Want', 'Lost old ones'),
  tx('17 Jan 2026', 'Zomato dinner', 'Lifestyle Enjoyment', 480, 'UPI', 'Want', 'Biryani'),
  tx('18 Jan 2026', 'Groceries - BigBasket', 'Life Infrastructure', 900, 'UPI', 'Need', 'Restock'),
  tx('18 Jan 2026', 'Cooking gas', 'Life Infrastructure', 900, 'UPI', 'Need', 'Cylinder refill'),
  tx('18 Jan 2026', 'Swiggy ice cream', 'Lifestyle Enjoyment', 180, 'UPI', 'Want', 'Dessert craving'),
  tx('19 Jan 2026', 'Auto to metro', 'Life Infrastructure', 40, 'Cash', 'Need', 'Commute'),
  tx('19 Jan 2026', 'Chai + vada pav', 'Lifestyle Enjoyment', 60, 'Cash', 'Want', 'Lunch'),
  tx('20 Jan 2026', 'Uber rides', 'Life Infrastructure', 190, 'UPI', 'Need', 'Rain day'),
  tx('20 Jan 2026', 'Swiggy lunch', 'Lifestyle Enjoyment', 260, 'UPI', 'Want', 'Office order'),
  tx('21 Jan 2026', 'Groceries - Zepto', 'Life Infrastructure', 320, 'UPI', 'Need', 'Quick run'),
  tx('21 Jan 2026', 'Haircut + grooming', 'Lifestyle Enjoyment', 500, 'Cash', 'Want', 'Salon visit'),
  tx('22 Jan 2026', 'Team dinner', 'Relationships & Generosity', 600, 'UPI', 'Want', 'Office team'),
  tx('22 Jan 2026', 'Uber home', 'Life Infrastructure', 250, 'UPI', 'Need', 'Late night'),
  tx('23 Jan 2026', 'Petrol', 'Life Infrastructure', 700, 'Debit Card', 'Need', 'Bike fuel'),
  tx('23 Jan 2026', 'Swiggy dinner', 'Lifestyle Enjoyment', 340, 'UPI', 'Want', 'Chinese food'),
  tx('24 Jan 2026', 'Concert tickets', 'Lifestyle Enjoyment', 1500, 'Credit Card', 'Want', 'Weekend plan'),
  tx('24 Jan 2026', 'Dinner out post concert', 'Lifestyle Enjoyment', 900, 'Credit Card', 'Want', 'Late dinner'),
  tx('24 Jan 2026', 'Uber', 'Life Infrastructure', 350, 'UPI', 'Need', 'Concert venue'),
  tx('25 Jan 2026', 'Groceries - DMart', 'Life Infrastructure', 800, 'Cash', 'Need', 'Weekly buy'),
  tx('25 Jan 2026', 'Laundry', 'Life Infrastructure', 200, 'UPI', 'Need', 'Dry cleaning'),
  tx('26 Jan 2026', 'Brunch out', 'Lifestyle Enjoyment', 650, 'UPI', 'Want', 'Holiday brunch'),
  tx('26 Jan 2026', 'Shopping - jacket', 'Lifestyle Enjoyment', 1800, 'Credit Card', 'Want', 'Winter sale'),
  tx('27 Jan 2026', 'Metro recharge', 'Life Infrastructure', 200, 'UPI', 'Need', 'Top up'),
  tx('27 Jan 2026', 'Chai tapri', 'Lifestyle Enjoyment', 30, 'Cash', 'Want', 'Chai break'),
  tx('28 Jan 2026', 'Groceries - Zepto', 'Life Infrastructure', 290, 'UPI', 'Need', 'Essentials'),
  tx('28 Jan 2026', 'Swiggy lunch', 'Lifestyle Enjoyment', 230, 'UPI', 'Want', 'Dal makhani'),
  tx('29 Jan 2026', 'Medicine', 'Life Infrastructure', 350, 'Cash', 'Need', 'Cold meds'),
  tx('29 Jan 2026', 'Auto', 'Life Infrastructure', 50, 'Cash', 'Need', 'Short ride'),
  tx('30 Jan 2026', 'Uber', 'Life Infrastructure', 170, 'UPI', 'Need', 'Commute'),
  tx('30 Jan 2026', 'Canteen lunch', 'Lifestyle Enjoyment', 120, 'Cash', 'Want', 'Office'),
  tx('31 Jan 2026', 'Swiggy dinner', 'Lifestyle Enjoyment', 300, 'UPI', 'Want', 'Month end'),
  tx('31 Jan 2026', 'Paan + chai', 'Lifestyle Enjoyment', 50, 'Cash', 'Want', 'Night walk'),

  // ── February 2026 ────────────────────────────────────────────────────
  tx('01 Feb 2026', 'House Rent', 'Life Infrastructure', 12000, 'Bank Transfer', 'Need', 'Monthly rent'),
  tx('01 Feb 2026', 'Groceries - BigBasket', 'Life Infrastructure', 1500, 'UPI', 'Need', 'Monthly stock'),
  tx('01 Feb 2026', 'Chai tapri', 'Lifestyle Enjoyment', 30, 'Cash', 'Want', 'Morning chai'),
  tx('02 Feb 2026', 'Metro Card Recharge', 'Life Infrastructure', 500, 'UPI', 'Need', 'Monthly pass'),
  tx('02 Feb 2026', 'Mobile Recharge', 'Life Infrastructure', 299, 'UPI', 'Need', 'Airtel plan'),
  tx('02 Feb 2026', 'Swiggy lunch', 'Lifestyle Enjoyment', 280, 'UPI', 'Want', 'Office order'),
  tx('03 Feb 2026', 'Gym Membership', 'Performance & Growth', 1500, 'Debit Card', 'Need', 'Monthly gym'),
  tx('03 Feb 2026', 'Uber to office', 'Life Infrastructure', 180, 'UPI', 'Need', 'Late start'),
  tx('03 Feb 2026', 'Chai + samosa', 'Lifestyle Enjoyment', 50, 'Cash', 'Want', 'Snack break'),
  tx('04 Feb 2026', 'Netflix', 'Lifestyle Enjoyment', 199, 'Credit Card', 'Want', 'Monthly sub'),
  tx('04 Feb 2026', 'Groceries - Zepto', 'Life Infrastructure', 380, 'UPI', 'Need', 'Fruits veggies'),
  tx('04 Feb 2026', 'Canteen lunch', 'Lifestyle Enjoyment', 120, 'Cash', 'Want', 'Office'),
  tx('05 Feb 2026', 'Electricity Bill', 'Life Infrastructure', 1300, 'UPI', 'Need', 'Feb bill'),
  tx('05 Feb 2026', 'Dinner with college friends', 'Relationships & Generosity', 1100, 'UPI', 'Want', 'Reunion dinner'),
  tx('05 Feb 2026', 'Uber home', 'Life Infrastructure', 280, 'UPI', 'Need', 'Late cab'),
  tx('06 Feb 2026', 'Petrol', 'Life Infrastructure', 800, 'Debit Card', 'Need', 'Bike fuel'),
  tx('06 Feb 2026', 'Coffee - Third Wave', 'Lifestyle Enjoyment', 300, 'UPI', 'Want', 'Friday coffee'),
  tx('06 Feb 2026', 'Zomato dinner', 'Lifestyle Enjoyment', 450, 'UPI', 'Want', 'Pizza night'),
  tx('07 Feb 2026', 'SIP - Mutual Fund', 'Future Me', 3000, 'Bank Transfer', 'Saving', 'Trying to be better'),
  tx('07 Feb 2026', 'Movie tickets + snacks', 'Lifestyle Enjoyment', 850, 'UPI', 'Want', 'Weekend movie'),
  tx('07 Feb 2026', 'Shopping - t-shirts', 'Lifestyle Enjoyment', 1500, 'Credit Card', 'Want', 'Zara sale'),
  tx('07 Feb 2026', 'Uber rides', 'Life Infrastructure', 300, 'UPI', 'Need', 'Mall trip'),
  tx('08 Feb 2026', 'Groceries - DMart', 'Life Infrastructure', 1100, 'Cash', 'Need', 'Weekly buy'),
  tx('08 Feb 2026', 'Brunch out', 'Lifestyle Enjoyment', 600, 'UPI', 'Want', 'Sunday brunch'),
  tx('08 Feb 2026', 'Laundry', 'Life Infrastructure', 200, 'UPI', 'Need', 'Dry cleaning'),
  tx('08 Feb 2026', 'OM SAI KRUPA Footwear', 'Lifestyle Enjoyment', 200, 'UPI', 'Want', ''),
  tx('08 Feb 2026', 'Transfer to Piyush Kumar', 'Relationships & Generosity', 541, 'UPI', 'Want', ''),
  tx('08 Feb 2026', 'Transfer to Vagmare Surya Prakash', 'Relationships & Generosity', 731, 'UPI', 'Want', ''),
  tx('09 Feb 2026', 'Hayagreeva PG Rent', 'Life Infrastructure', 12500, 'UPI', 'Need', 'Monthly PG rent'),
  tx('09 Feb 2026', 'Auto to metro', 'Life Infrastructure', 40, 'Cash', 'Need', 'Commute'),
  tx('09 Feb 2026', 'Swiggy lunch', 'Lifestyle Enjoyment', 250, 'UPI', 'Want', 'Chole bhature'),
  tx('09 Feb 2026', 'Chai tapri', 'Lifestyle Enjoyment', 30, 'Cash', 'Want', 'Evening chai'),
  tx('10 Feb 2026', 'Internet Bill', 'Life Infrastructure', 799, 'UPI', 'Need', 'Broadband'),
  tx('10 Feb 2026', 'Books - Amazon', 'Performance & Growth', 350, 'UPI', 'Need', 'Psychology of Money'),
  tx('10 Feb 2026', 'Uber', 'Life Infrastructure', 170, 'UPI', 'Need', 'Commute'),
  tx('10 Feb 2026', 'Transfer to Rathod Nithin', 'Relationships & Generosity', 152, 'UPI', 'Want', ''),
  tx('10 Feb 2026', 'Transfer to Anubhav Kumar Agarwal', 'Relationships & Generosity', 1408, 'UPI', 'Want', ''),
  tx('10 Feb 2026', 'Transfer to Kethamma Mukkera', 'Relationships & Generosity', 148, 'UPI', 'Want', ''),
  tx('11 Feb 2026', 'Groceries - Zepto', 'Life Infrastructure', 290, 'UPI', 'Need', 'Quick run'),
  tx('11 Feb 2026', 'Lunch treat for intern', 'Relationships & Generosity', 400, 'UPI', 'Want', 'Team bonding'),
  tx('11 Feb 2026', 'Rapido ride', 'Life Infrastructure', 126, 'UPI', 'Need', ''),
  tx('11 Feb 2026', 'Transfer to Shaik Mastanvali', 'Relationships & Generosity', 60, 'UPI', 'Want', ''),
  tx('11 Feb 2026', 'Google Asia Pacific subscription', 'Lifestyle Enjoyment', 100, 'UPI', 'Want', ''),
  tx('12 Feb 2026', 'Swiggy dinner', 'Lifestyle Enjoyment', 320, 'UPI', 'Want', 'Thai food'),
  tx('12 Feb 2026', 'Medicine', 'Life Infrastructure', 250, 'Cash', 'Need', 'Vitamins'),
  tx('12 Feb 2026', 'Spotify', 'Lifestyle Enjoyment', 119, 'Credit Card', 'Want', 'Monthly sub'),
  tx('12 Feb 2026', 'Uber India', 'Life Infrastructure', 82, 'UPI', 'Need', ''),
  tx('12 Feb 2026', 'Transfer to Kranthi Kumar', 'Relationships & Generosity', 160, 'UPI', 'Want', ''),
  tx('12 Feb 2026', 'Transfer to Battu Siva', 'Relationships & Generosity', 62, 'UPI', 'Want', ''),
  tx('13 Feb 2026', 'Valentine gift - perfume', 'Relationships & Generosity', 2200, 'Credit Card', 'Want', 'Gift for partner'),
  tx('13 Feb 2026', 'Flowers', 'Relationships & Generosity', 500, 'UPI', 'Want', 'Roses'),
  tx('13 Feb 2026', 'Haircut', 'Lifestyle Enjoyment', 300, 'Cash', 'Want', 'Grooming'),
  tx('13 Feb 2026', 'Transfer to Vankayalapaty Venkata Narayana', 'Relationships & Generosity', 79, 'UPI', 'Want', ''),
  tx('13 Feb 2026', 'Transfer to Adapa Subbarao', 'Relationships & Generosity', 62, 'UPI', 'Want', ''),
  tx('14 Feb 2026', 'Valentine dinner - fancy restaurant', 'Relationships & Generosity', 3500, 'Credit Card', 'Want', 'Date night'),
  tx('14 Feb 2026', 'Uber rides', 'Life Infrastructure', 400, 'UPI', 'Need', 'To and from restaurant'),
  tx('14 Feb 2026', 'Dessert', 'Lifestyle Enjoyment', 350, 'UPI', 'Want', 'Cake stop'),
  tx('15 Feb 2026', 'FD Deposit', 'Future Me', 2000, 'Bank Transfer', 'Saving', 'Quarterly FD'),
  tx('15 Feb 2026', 'Groceries - BigBasket', 'Life Infrastructure', 850, 'UPI', 'Need', 'Restock'),
  tx('15 Feb 2026', 'Swiggy dinner', 'Lifestyle Enjoyment', 300, 'UPI', 'Want', 'Lazy Sunday'),
  tx('15 Feb 2026', 'Transfer to Bhagwati', 'Relationships & Generosity', 20, 'UPI', 'Want', ''),
  tx('16 Feb 2026', 'Water Bill', 'Life Infrastructure', 200, 'UPI', 'Need', 'Quarterly'),
  tx('16 Feb 2026', 'Chai + vada pav', 'Lifestyle Enjoyment', 60, 'Cash', 'Want', 'Snack'),
  tx('17 Feb 2026', 'Uber rides', 'Life Infrastructure', 200, 'UPI', 'Need', 'Commute'),
  tx('17 Feb 2026', 'Swiggy lunch', 'Lifestyle Enjoyment', 270, 'UPI', 'Want', 'Paneer tikka'),
  tx('17 Feb 2026', 'Budget Babai - food', 'Lifestyle Enjoyment', 118, 'UPI', 'Want', ''),
  tx('17 Feb 2026', 'Transfer to Bojjagani Naveen', 'Relationships & Generosity', 81, 'UPI', 'Want', ''),
  tx('17 Feb 2026', 'Transfer to Nagarjuna Aravati', 'Relationships & Generosity', 54, 'UPI', 'Want', ''),
  tx('18 Feb 2026', 'Groceries - Zepto', 'Life Infrastructure', 350, 'UPI', 'Need', 'Essentials'),
  tx('18 Feb 2026', 'Auto rides', 'Life Infrastructure', 80, 'Cash', 'Need', 'Short trips'),
  tx('18 Feb 2026', 'IRCTC Train ticket', 'Life Infrastructure', 959, 'UPI', 'Need', 'Travel'),
  tx('18 Feb 2026', 'Transfer to Shailesh Kumar Yadav', 'Relationships & Generosity', 170, 'UPI', 'Want', ''),
  tx('18 Feb 2026', 'Transfer to Dudi Shiva Sai', 'Relationships & Generosity', 86, 'UPI', 'Want', ''),
  tx('18 Feb 2026', 'Transfer to Shaikh Inzamam', 'Relationships & Generosity', 69, 'UPI', 'Want', ''),
  tx('19 Feb 2026', 'Team treat', 'Relationships & Generosity', 600, 'UPI', 'Want', 'Project ship'),
  tx('19 Feb 2026', 'Paan', 'Lifestyle Enjoyment', 40, 'Cash', 'Want', 'After dinner'),
  tx('19 Feb 2026', 'Transfer to Krishna', 'Relationships & Generosity', 530, 'UPI', 'Want', ''),
  tx('19 Feb 2026', 'Transfer to Shuhukari Vinay', 'Relationships & Generosity', 122, 'UPI', 'Want', ''),
  tx('19 Feb 2026', 'Transfer to Kollepara Bhanu Prathap', 'Relationships & Generosity', 61, 'UPI', 'Want', ''),
  tx('20 Feb 2026', 'Petrol', 'Life Infrastructure', 700, 'Debit Card', 'Need', 'Bike fuel'),
  tx('20 Feb 2026', 'Dinner out', 'Lifestyle Enjoyment', 800, 'Credit Card', 'Want', 'Friday treat'),
  tx('20 Feb 2026', 'HungerBox - office food', 'Lifestyle Enjoyment', 66, 'UPI', 'Want', ''),
  tx('20 Feb 2026', 'Transfer to M Mallesh', 'Relationships & Generosity', 77, 'UPI', 'Want', ''),
  tx('20 Feb 2026', 'Transfer to Kollu Udaykiran', 'Relationships & Generosity', 60, 'UPI', 'Want', ''),
  tx('21 Feb 2026', 'Cafe with friends', 'Lifestyle Enjoyment', 400, 'UPI', 'Want', 'Saturday chill'),
  tx('21 Feb 2026', 'Amazon - Phone charger', 'Life Infrastructure', 500, 'Credit Card', 'Need', 'Old one broke'),
  tx('22 Feb 2026', 'Groceries - DMart', 'Life Infrastructure', 950, 'Cash', 'Need', 'Weekly buy'),
  tx('22 Feb 2026', 'Cooking gas', 'Life Infrastructure', 900, 'UPI', 'Need', 'Cylinder refill'),
  tx('22 Feb 2026', 'Medical - CMC Vellore', 'Life Infrastructure', 220, 'UPI', 'Need', ''),
  tx('23 Feb 2026', 'Metro recharge', 'Life Infrastructure', 200, 'UPI', 'Need', 'Top up'),
  tx('23 Feb 2026', 'Coffee Starbucks', 'Lifestyle Enjoyment', 350, 'UPI', 'Want', 'Monday coffee'),
  tx('23 Feb 2026', 'Transfer to Sure Sivaramakrishna', 'Relationships & Generosity', 102, 'UPI', 'Want', ''),
  tx('23 Feb 2026', 'Transfer to Golla Mahesh', 'Relationships & Generosity', 61, 'UPI', 'Want', ''),
  tx('24 Feb 2026', 'Swiggy lunch', 'Lifestyle Enjoyment', 240, 'UPI', 'Want', 'Quick bite'),
  tx('24 Feb 2026', 'Uber', 'Life Infrastructure', 160, 'UPI', 'Need', 'Late meeting'),
  tx('24 Feb 2026', 'Roppen Transportation', 'Life Infrastructure', 116, 'UPI', 'Need', ''),
  tx('24 Feb 2026', 'Transfer to Boddu Srinivasarao', 'Relationships & Generosity', 62, 'UPI', 'Want', ''),
  tx('25 Feb 2026', 'Groceries - Zepto', 'Life Infrastructure', 280, 'UPI', 'Need', 'Milk curd bread'),
  tx('25 Feb 2026', 'Chai tapri', 'Lifestyle Enjoyment', 30, 'Cash', 'Want', 'Chai break'),
  tx('25 Feb 2026', 'Transfer to Sunkara Abhinava Sai', 'Relationships & Generosity', 73, 'UPI', 'Want', ''),
  tx('25 Feb 2026', 'Transfer to Kota Saketh', 'Relationships & Generosity', 63, 'UPI', 'Want', ''),
  tx('26 Feb 2026', 'Drinks with old friends', 'Lifestyle Enjoyment', 1200, 'Credit Card', 'Want', 'Thursday night'),
  tx('26 Feb 2026', 'Uber late night', 'Life Infrastructure', 320, 'UPI', 'Need', 'Cab home'),
  tx('26 Feb 2026', 'Uber India', 'Life Infrastructure', 89, 'UPI', 'Need', ''),
  tx('26 Feb 2026', 'Transfer to Kathula Raghu', 'Relationships & Generosity', 87, 'UPI', 'Want', ''),
  tx('26 Feb 2026', 'Transfer to Manapadu Devendar', 'Relationships & Generosity', 63, 'UPI', 'Want', ''),
  tx('26 Feb 2026', 'Savings transfer to Anuj', 'Future Me', 1000, 'UPI', 'Saving', ''),
  tx('27 Feb 2026', 'Zomato dinner', 'Lifestyle Enjoyment', 400, 'UPI', 'Want', 'Friday order'),
  tx('27 Feb 2026', 'Parking', 'Life Infrastructure', 50, 'Cash', 'Need', 'Office parking'),
  tx('27 Feb 2026', 'Netflix subscription', 'Lifestyle Enjoyment', 199, 'UPI', 'Want', 'Monthly sub'),
  tx('27 Feb 2026', 'Transfer to Thallapally Krishnamurthy', 'Relationships & Generosity', 65, 'UPI', 'Want', ''),
  tx('27 Feb 2026', 'Transfer to Chilukuri Veera Naga Soma', 'Relationships & Generosity', 62, 'UPI', 'Want', ''),
  tx('28 Feb 2026', 'Groceries', 'Life Infrastructure', 600, 'UPI', 'Need', 'Month end stock'),
  tx('28 Feb 2026', 'Swiggy dessert', 'Lifestyle Enjoyment', 200, 'UPI', 'Want', 'Cheesecake'),
  tx('28 Feb 2026', 'Auto', 'Life Infrastructure', 50, 'Cash', 'Need', 'Short ride'),
  tx('28 Feb 2026', 'Savings to account', 'Future Me', 300, 'UPI', 'Saving', ''),
  tx('28 Feb 2026', 'Transfer to Bhagwati', 'Relationships & Generosity', 10, 'UPI', 'Want', ''),

  // ── March 2026 ───────────────────────────────────────────────────────
  tx('01 Mar 2026', 'House Rent', 'Life Infrastructure', 12000, 'Bank Transfer', 'Need', 'Monthly rent'),
  tx('01 Mar 2026', 'Groceries - BigBasket', 'Life Infrastructure', 1800, 'UPI', 'Need', 'Monthly grocery stock'),
  tx('01 Mar 2026', 'Chai tapri', 'Lifestyle Enjoyment', 30, 'Cash', 'Want', 'Morning chai'),
  tx('01 Mar 2026', 'Swiggy lunch', 'Lifestyle Enjoyment', 280, 'UPI', 'Want', 'Biryani'),
  tx('01 Mar 2026', 'Alpha Salon', 'Lifestyle Enjoyment', 299, 'UPI', 'Want', ''),
  tx('01 Mar 2026', 'Transfer to Gaddam Lokesh', 'Relationships & Generosity', 141, 'UPI', 'Want', ''),
  tx('02 Mar 2026', 'Metro Card Recharge', 'Life Infrastructure', 500, 'UPI', 'Need', 'Monthly commute'),
  tx('02 Mar 2026', 'Mobile Recharge', 'Life Infrastructure', 299, 'UPI', 'Need', 'Airtel plan'),
  tx('02 Mar 2026', 'Chai + samosa', 'Lifestyle Enjoyment', 50, 'Cash', 'Want', 'Office break'),
  tx('02 Mar 2026', 'Uber India', 'Life Infrastructure', 69, 'UPI', 'Need', ''),
  tx('02 Mar 2026', 'Uber India ride', 'Life Infrastructure', 17, 'UPI', 'Need', ''),
  tx('03 Mar 2026', 'Gym Membership', 'Performance & Growth', 1500, 'Debit Card', 'Need', 'Monthly gym'),
  tx('03 Mar 2026', 'Uber to office', 'Life Infrastructure', 180, 'UPI', 'Need', 'Late for meeting'),
  tx('03 Mar 2026', 'Zepto snacks', 'Life Infrastructure', 320, 'UPI', 'Need', 'Chips, biscuits, juice'),
  tx('04 Mar 2026', 'Netflix Subscription', 'Lifestyle Enjoyment', 199, 'Credit Card', 'Want', 'Monthly sub'),
  tx('04 Mar 2026', 'Lunch canteen', 'Lifestyle Enjoyment', 120, 'Cash', 'Want', 'Office lunch'),
  tx('04 Mar 2026', 'Auto rickshaw', 'Life Infrastructure', 60, 'Cash', 'Need', 'Metro to office'),
  tx('04 Mar 2026', 'Transfer to Doddi Divya', 'Relationships & Generosity', 74, 'UPI', 'Want', ''),
  tx('04 Mar 2026', 'Transfer to Mankali Rakesh', 'Relationships & Generosity', 53, 'UPI', 'Want', ''),
  tx('05 Mar 2026', 'Dinner with friends', 'Relationships & Generosity', 1200, 'UPI', 'Want', 'Birthday dinner for Rahul'),
  tx('05 Mar 2026', 'Uber back home', 'Life Infrastructure', 220, 'UPI', 'Need', 'Late night cab'),
  tx('05 Mar 2026', 'Tea + biscuits', 'Lifestyle Enjoyment', 40, 'Cash', 'Want', 'Evening snack'),
  tx('05 Mar 2026', 'Transfer to Amresh Kumar Kotagiri', 'Relationships & Generosity', 77, 'UPI', 'Want', ''),
  tx('05 Mar 2026', 'Transfer to Sivakumar', 'Relationships & Generosity', 53, 'UPI', 'Want', ''),
  tx('06 Mar 2026', 'Groceries - Zepto', 'Life Infrastructure', 650, 'UPI', 'Need', 'Fruits and veggies'),
  tx('06 Mar 2026', 'Petrol', 'Life Infrastructure', 800, 'Debit Card', 'Need', 'Bike fuel'),
  tx('06 Mar 2026', 'Swiggy dinner', 'Lifestyle Enjoyment', 450, 'UPI', 'Want', 'Pizza night'),
  tx('06 Mar 2026', 'Swiggy Ltd order', 'Lifestyle Enjoyment', 238, 'UPI', 'Want', ''),
  tx('06 Mar 2026', 'Uber India', 'Life Infrastructure', 52, 'UPI', 'Need', ''),
  tx('06 Mar 2026', 'Transfer to Katam Ramesh', 'Relationships & Generosity', 66, 'UPI', 'Want', ''),
  tx('07 Mar 2026', 'SIP - Mutual Fund', 'Future Me', 5000, 'Bank Transfer', 'Saving', 'Monthly SIP'),
  tx('07 Mar 2026', 'Movie tickets', 'Lifestyle Enjoyment', 600, 'UPI', 'Want', 'Weekend movie'),
  tx('07 Mar 2026', 'Popcorn + drinks', 'Lifestyle Enjoyment', 350, 'Cash', 'Want', 'At the theater'),
  tx('07 Mar 2026', 'Zomato dinner', 'Lifestyle Enjoyment', 550, 'UPI', 'Want', 'Post movie dinner'),
  tx('07 Mar 2026', 'Uber rides', 'Life Infrastructure', 300, 'UPI', 'Need', 'To and from mall'),
  tx('07 Mar 2026', 'SWIGGY order', 'Lifestyle Enjoyment', 245, 'UPI', 'Want', ''),
  tx('07 Mar 2026', 'Mobile recharge Jio', 'Life Infrastructure', 19, 'UPI', 'Need', ''),
  tx('07 Mar 2026', 'Google Play subscription', 'Lifestyle Enjoyment', 2, 'UPI', 'Want', ''),
  tx('07 Mar 2026', 'Transfer to Bhagwati', 'Relationships & Generosity', 10, 'UPI', 'Want', ''),
  tx('07 Mar 2026', 'Transfer to Thummida Saloman', 'Relationships & Generosity', 100, 'UPI', 'Want', ''),
  tx('08 Mar 2026', 'Electricity Bill', 'Life Infrastructure', 1400, 'UPI', 'Need', 'March bill'),
  tx('08 Mar 2026', 'Brunch out', 'Lifestyle Enjoyment', 750, 'Credit Card', 'Want', 'Sunday brunch'),
  tx('08 Mar 2026', 'Groceries - DMart', 'Life Infrastructure', 1200, 'Cash', 'Need', 'Weekly bulk buy'),
  tx('08 Mar 2026', 'Savings to Nandani', 'Future Me', 2500, 'UPI', 'Saving', ''),
  tx('08 Mar 2026', 'Savings to Anuj', 'Future Me', 2500, 'UPI', 'Saving', ''),
  tx('09 Mar 2026', 'Coffee - Starbucks', 'Lifestyle Enjoyment', 350, 'UPI', 'Want', 'Monday motivation'),
  tx('09 Mar 2026', 'Auto to metro', 'Life Infrastructure', 40, 'Cash', 'Need', 'Commute'),
  tx('09 Mar 2026', 'Roppen Transportation', 'Life Infrastructure', 110, 'UPI', 'Need', ''),
  tx('09 Mar 2026', 'Transfer to Chintu Srivasatav', 'Relationships & Generosity', 57, 'UPI', 'Want', ''),
  tx('10 Mar 2026', 'Uber rides', 'Life Infrastructure', 190, 'UPI', 'Need', 'Rain day cab'),
  tx('10 Mar 2026', 'Online Course - Udemy', 'Performance & Growth', 499, 'Credit Card', 'Need', 'Python course'),
  tx('10 Mar 2026', 'Chai tapri', 'Lifestyle Enjoyment', 30, 'Cash', 'Want', 'Evening chai'),
  tx('10 Mar 2026', 'Transfer to Kranthi Kumar', 'Relationships & Generosity', 120, 'UPI', 'Want', ''),
  tx('10 Mar 2026', 'Transfer to MD Seidur Rahaman', 'Relationships & Generosity', 73, 'UPI', 'Want', ''),
  tx('10 Mar 2026', 'Transfer to Gurajala Madhu Babu', 'Relationships & Generosity', 65, 'UPI', 'Want', ''),
  tx('11 Mar 2026', 'Lunch with colleague', 'Relationships & Generosity', 400, 'UPI', 'Want', 'Team lunch'),
  tx('11 Mar 2026', 'Amazon - Phone case', 'Lifestyle Enjoyment', 299, 'Credit Card', 'Want', 'New case'),
  tx('11 Mar 2026', 'Gappe Vappe restaurant', 'Lifestyle Enjoyment', 450, 'UPI', 'Want', ''),
  tx('11 Mar 2026', 'Laxmi Foods', 'Lifestyle Enjoyment', 140, 'UPI', 'Want', ''),
  tx('11 Mar 2026', 'KFC', 'Lifestyle Enjoyment', 709, 'UPI', 'Want', ''),
  tx('11 Mar 2026', 'Shadowfax delivery', 'Life Infrastructure', 61, 'UPI', 'Need', ''),
  tx('11 Mar 2026', 'Transfer to Thoka Siddappa', 'Relationships & Generosity', 100, 'UPI', 'Want', ''),
  tx('11 Mar 2026', 'Transfer to Radharapu Madhusudhan', 'Relationships & Generosity', 147, 'UPI', 'Want', ''),
  tx('11 Mar 2026', 'Transfer to Shaik Junaid', 'Relationships & Generosity', 69, 'UPI', 'Want', ''),
  tx('12 Mar 2026', 'Groceries - Zepto', 'Life Infrastructure', 480, 'UPI', 'Need', 'Milk, bread, eggs'),
  tx('12 Mar 2026', 'Swiggy lunch', 'Lifestyle Enjoyment', 200, 'UPI', 'Want', 'Office lunch'),
  tx('12 Mar 2026', 'Medicine', 'Life Infrastructure', 350, 'Cash', 'Need', 'Cold medicine'),
  tx('12 Mar 2026', 'Uber India', 'Life Infrastructure', 40, 'UPI', 'Need', ''),
  tx('12 Mar 2026', 'Transfer to Kethavath Veeresh', 'Relationships & Generosity', 72, 'UPI', 'Want', ''),
  tx('13 Mar 2026', 'Drinks with friends', 'Relationships & Generosity', 1500, 'Credit Card', 'Want', 'Friday night out'),
  tx('13 Mar 2026', 'Uber late night', 'Life Infrastructure', 350, 'UPI', 'Need', 'Cab home'),
  tx('13 Mar 2026', 'Street food', 'Lifestyle Enjoyment', 150, 'Cash', 'Want', 'Momos + golgappa'),
  tx('13 Mar 2026', 'SAVESAGE SOLUTIONS', 'Performance & Growth', 319, 'UPI', 'Need', ''),
  tx('13 Mar 2026', 'Transfer to Kesari Akash Singh', 'Relationships & Generosity', 94, 'UPI', 'Want', ''),
  tx('13 Mar 2026', 'Transfer to Kothapelli Narendhar', 'Relationships & Generosity', 58, 'UPI', 'Want', ''),
  tx('14 Mar 2026', 'Gift for mom', 'Relationships & Generosity', 2000, 'Debit Card', 'Want', 'Birthday gift'),
  tx('14 Mar 2026', 'Cake', 'Relationships & Generosity', 600, 'UPI', 'Want', 'Birthday cake'),
  tx('14 Mar 2026', 'Family dinner out', 'Relationships & Generosity', 2500, 'Credit Card', 'Want', 'Mom birthday dinner'),
  tx('14 Mar 2026', 'Uber rides', 'Life Infrastructure', 250, 'UPI', 'Need', 'To restaurant and back'),
  tx('14 Mar 2026', 'Hayagreeva PG Rent', 'Life Infrastructure', 9500, 'UPI', 'Need', 'Monthly PG rent'),
  tx('14 Mar 2026', 'Dominos Pizza', 'Lifestyle Enjoyment', 221, 'UPI', 'Want', ''),
  tx('14 Mar 2026', 'Transfer to Bhagwati', 'Relationships & Generosity', 10, 'UPI', 'Want', ''),
  tx('15 Mar 2026', 'FD Deposit', 'Future Me', 3000, 'Bank Transfer', 'Saving', 'Quarterly FD'),
  tx('15 Mar 2026', 'Groceries - BigBasket', 'Life Infrastructure', 950, 'UPI', 'Need', 'Weekly restock'),
  tx('15 Mar 2026', 'Laundry', 'Life Infrastructure', 200, 'UPI', 'Need', 'Dry cleaning'),
  tx('16 Mar 2026', 'Water Bill', 'Life Infrastructure', 200, 'UPI', 'Need', 'Quarterly'),
  tx('16 Mar 2026', 'Chai + vada pav', 'Lifestyle Enjoyment', 60, 'Cash', 'Want', 'Lunch snack'),
  tx('16 Mar 2026', 'Metro recharge', 'Life Infrastructure', 200, 'UPI', 'Need', 'Top up'),
  tx('16 Mar 2026', 'Uber India', 'Life Infrastructure', 68, 'UPI', 'Need', ''),
  tx('16 Mar 2026', 'Transfer to Saranam Ravi Sankar', 'Relationships & Generosity', 31, 'UPI', 'Want', ''),
  tx('17 Mar 2026', 'Swiggy orders', 'Lifestyle Enjoyment', 380, 'Credit Card', 'Want', 'Lunch delivery'),
  tx('17 Mar 2026', 'Books - Flipkart', 'Performance & Growth', 450, 'UPI', 'Need', 'Atomic Habits'),
  tx('17 Mar 2026', 'Transfer to Kethavath Shankar', 'Relationships & Generosity', 153, 'UPI', 'Want', ''),
  tx('17 Mar 2026', 'Transfer to Ismail Khan', 'Relationships & Generosity', 60, 'UPI', 'Want', ''),
  tx('18 Mar 2026', 'Haircut', 'Lifestyle Enjoyment', 300, 'Cash', 'Want', 'Monthly trim'),
  tx('18 Mar 2026', 'Groceries - Zepto', 'Life Infrastructure', 290, 'UPI', 'Need', 'Quick essentials'),
  tx('18 Mar 2026', 'Chai tapri', 'Lifestyle Enjoyment', 30, 'Cash', 'Want', 'Chai break'),
  tx('18 Mar 2026', 'Zomato order 1', 'Lifestyle Enjoyment', 1439, 'UPI', 'Want', ''),
  tx('18 Mar 2026', 'Zomato order 2', 'Lifestyle Enjoyment', 75, 'UPI', 'Want', ''),
  tx('18 Mar 2026', 'Transfer to Nagesh Nanduru', 'Relationships & Generosity', 250, 'UPI', 'Want', ''),
  tx('18 Mar 2026', 'Transfer to B Balakrishna', 'Relationships & Generosity', 104, 'UPI', 'Want', ''),
  tx('18 Mar 2026', 'Transfer to Premnarayan Patel', 'Relationships & Generosity', 91, 'UPI', 'Want', ''),
  tx('18 Mar 2026', 'Transfer to Pola Uday', 'Relationships & Generosity', 53, 'UPI', 'Want', ''),
  tx('19 Mar 2026', 'Amazon - Headphones', 'Lifestyle Enjoyment', 1500, 'Credit Card', 'Want', 'Replacement buds'),
  tx('19 Mar 2026', 'Lunch - office canteen', 'Lifestyle Enjoyment', 110, 'Cash', 'Want', 'Thali'),
  tx('19 Mar 2026', 'USHA MARTIN UNIVERSITY fee', 'Performance & Growth', 500, 'UPI', 'Need', ''),
  tx('19 Mar 2026', 'Savings to account', 'Future Me', 250, 'UPI', 'Saving', ''),
  tx('19 Mar 2026', 'Transfer to Sujeet Sharma', 'Relationships & Generosity', 67, 'UPI', 'Want', ''),
  tx('19 Mar 2026', 'Transfer to Balagonda Badrinath', 'Relationships & Generosity', 60, 'UPI', 'Want', ''),
  tx('20 Mar 2026', 'Petrol', 'Life Infrastructure', 700, 'Debit Card', 'Need', 'Bike fuel'),
  tx('20 Mar 2026', 'Dinner out', 'Lifestyle Enjoyment', 900, 'Credit Card', 'Want', 'Friday treat'),
  tx('20 Mar 2026', 'Parking', 'Life Infrastructure', 50, 'Cash', 'Need', 'Mall parking'),
  tx('20 Mar 2026', 'Ice cream', 'Lifestyle Enjoyment', 150, 'UPI', 'Want', 'Baskin Robbins'),
  tx('20 Mar 2026', 'Uber India', 'Life Infrastructure', 51, 'UPI', 'Need', ''),
  tx('20 Mar 2026', 'Transfer to Kandula Vijaya Muni Reddy', 'Relationships & Generosity', 75, 'UPI', 'Want', ''),
  tx('21 Mar 2026', 'Charity donation', 'Relationships & Generosity', 500, 'UPI', 'Want', 'Monthly donation'),
  tx('21 Mar 2026', 'Shopping - clothes', 'Lifestyle Enjoyment', 2200, 'Credit Card', 'Want', 'New shirt + jeans'),
  tx('21 Mar 2026', 'Cafe with friends', 'Lifestyle Enjoyment', 450, 'UPI', 'Want', 'Third Wave Coffee'),
  tx('21 Mar 2026', 'Auto rides', 'Life Infrastructure', 120, 'Cash', 'Need', 'Market trip'),
  tx('21 Mar 2026', 'Dominos Pizza', 'Lifestyle Enjoyment', 297, 'UPI', 'Want', ''),
  tx('21 Mar 2026', 'Dot and Key Skincare', 'Lifestyle Enjoyment', 447, 'UPI', 'Want', ''),
  tx('21 Mar 2026', 'Thedermaco skincare', 'Lifestyle Enjoyment', 474, 'UPI', 'Want', ''),
  tx('21 Mar 2026', 'Transfer to Bhagwati', 'Relationships & Generosity', 10, 'UPI', 'Want', ''),
  tx('22 Mar 2026', 'PPF Contribution', 'Future Me', 2000, 'Bank Transfer', 'Saving', 'Monthly PPF'),
  tx('22 Mar 2026', 'Groceries - DMart', 'Life Infrastructure', 1100, 'Cash', 'Need', 'Weekly buy'),
  tx('22 Mar 2026', 'Swiggy dinner', 'Lifestyle Enjoyment', 320, 'UPI', 'Want', 'Lazy Sunday dinner'),
  tx('22 Mar 2026', 'Savings to Ankush Shop', 'Future Me', 30000, 'UPI', 'Saving', ''),
  tx('22 Mar 2026', 'WEB UPI payment', 'Performance & Growth', 2444, 'UPI', 'Need', ''),
  tx('23 Mar 2026', 'Uber to office', 'Life Infrastructure', 200, 'UPI', 'Need', 'Running late'),
  tx('23 Mar 2026', 'Chai + sandwich', 'Lifestyle Enjoyment', 80, 'Cash', 'Want', 'Evening snack'),
  tx('23 Mar 2026', 'Transfer to Sabhavat Saikumar', 'Relationships & Generosity', 155, 'UPI', 'Want', ''),
  tx('23 Mar 2026', 'Transfer to Paramesh', 'Relationships & Generosity', 60, 'UPI', 'Want', ''),
  tx('24 Mar 2026', 'Internet Bill', 'Life Infrastructure', 799, 'UPI', 'Need', 'Broadband monthly'),
  tx('24 Mar 2026', 'Zepto groceries', 'Life Infrastructure', 350, 'UPI', 'Need', 'Milk, curd, bread'),
  tx('24 Mar 2026', 'Swiggy lunch', 'Lifestyle Enjoyment', 250, 'UPI', 'Want', 'Butter chicken'),
  tx('24 Mar 2026', 'AM TO PM FOOD COURT', 'Lifestyle Enjoyment', 430, 'UPI', 'Want', ''),
  tx('24 Mar 2026', 'Lalu Hotel', 'Lifestyle Enjoyment', 60, 'UPI', 'Want', ''),
  tx('24 Mar 2026', 'Uber India', 'Life Infrastructure', 47, 'UPI', 'Need', ''),
  tx('24 Mar 2026', 'Transfer to Mudavath Raju', 'Relationships & Generosity', 266, 'UPI', 'Want', ''),
  tx('24 Mar 2026', 'Transfer to SK Arifali', 'Relationships & Generosity', 2000, 'UPI', 'Want', ''),
  tx('25 Mar 2026', 'Spotify', 'Lifestyle Enjoyment', 119, 'Credit Card', 'Want', 'Monthly sub'),
  tx('25 Mar 2026', 'Auto + metro', 'Life Infrastructure', 80, 'Cash', 'Need', 'Commute'),
  tx('25 Mar 2026', 'Jio Prepaid Recharge', 'Life Infrastructure', 899, 'UPI', 'Need', ''),
  tx('25 Mar 2026', 'Transfer to Mudavath Govind', 'Relationships & Generosity', 180, 'UPI', 'Want', ''),
  tx('25 Mar 2026', 'Transfer to Mohammed Arman', 'Relationships & Generosity', 62, 'UPI', 'Want', ''),
  tx('26 Mar 2026', 'Team treat', 'Relationships & Generosity', 800, 'UPI', 'Want', 'Project completion'),
  tx('26 Mar 2026', 'Uber home', 'Life Infrastructure', 170, 'UPI', 'Need', 'Late evening'),
  tx('26 Mar 2026', 'Paan', 'Lifestyle Enjoyment', 40, 'Cash', 'Want', 'After dinner'),
  tx('26 Mar 2026', 'Momos Lover', 'Lifestyle Enjoyment', 115, 'UPI', 'Want', ''),
  tx('26 Mar 2026', 'Savings transfer', 'Future Me', 1000, 'UPI', 'Saving', ''),
  tx('26 Mar 2026', 'DISTRICT Movies', 'Lifestyle Enjoyment', 734, 'UPI', 'Want', ''),
  tx('26 Mar 2026', 'Transfer to Gaddam Surya Teja Reddy', 'Relationships & Generosity', 107, 'UPI', 'Want', ''),
  tx('26 Mar 2026', 'Transfer to Sudu', 'Relationships & Generosity', 200, 'UPI', 'Want', ''),
  tx('26 Mar 2026', 'Transfer to Vijaykumar Noubade', 'Relationships & Generosity', 45, 'UPI', 'Want', ''),
  tx('27 Mar 2026', 'Dinner out', 'Lifestyle Enjoyment', 1100, 'Credit Card', 'Want', 'Korean BBQ'),
  tx('27 Mar 2026', 'Dessert', 'Lifestyle Enjoyment', 300, 'UPI', 'Want', 'Theobroma'),
  tx('27 Mar 2026', 'Uber rides', 'Life Infrastructure', 280, 'UPI', 'Need', 'Friday night cab'),
  tx('27 Mar 2026', 'Uber India', 'Life Infrastructure', 71, 'UPI', 'Need', ''),
  tx('27 Mar 2026', 'Netflix subscription', 'Lifestyle Enjoyment', 199, 'UPI', 'Want', ''),
  tx('27 Mar 2026', 'Nawab Restaurant', 'Lifestyle Enjoyment', 20, 'UPI', 'Want', ''),
  tx('27 Mar 2026', 'Transfer to Manoj HRC', 'Relationships & Generosity', 730, 'UPI', 'Want', ''),
  tx('28 Mar 2026', 'Groceries - BigBasket', 'Life Infrastructure', 1400, 'UPI', 'Need', 'Monthly restock big'),
  tx('28 Mar 2026', 'Salon', 'Lifestyle Enjoyment', 500, 'Cash', 'Want', 'Facial + cleanup'),
  tx('28 Mar 2026', 'Zomato brunch', 'Lifestyle Enjoyment', 650, 'UPI', 'Want', 'Weekend brunch order'),
  tx('28 Mar 2026', 'Petrol', 'Life Infrastructure', 500, 'Debit Card', 'Need', 'Bike top up'),
  tx('28 Mar 2026', 'AM TO PM FOOD COURT', 'Lifestyle Enjoyment', 925, 'UPI', 'Want', ''),
  tx('28 Mar 2026', 'PVR INOX - movies', 'Lifestyle Enjoyment', 785, 'UPI', 'Want', ''),
  tx('28 Mar 2026', 'Transfer to Vadthya Lokesh', 'Relationships & Generosity', 86, 'UPI', 'Want', ''),
  tx('28 Mar 2026', 'Transfer to Krishna', 'Relationships & Generosity', 1, 'UPI', 'Want', ''),
  tx('28 Mar 2026', 'Transfer to Kethavath Srinivasulu', 'Relationships & Generosity', 85, 'UPI', 'Want', ''),
  tx('28 Mar 2026', 'Transfer to Bhagwati', 'Relationships & Generosity', 20, 'UPI', 'Want', ''),
  tx('29 Mar 2026', 'Cooking gas', 'Life Infrastructure', 900, 'UPI', 'Need', 'Cylinder refill'),
  tx('29 Mar 2026', 'Groceries - Zepto', 'Life Infrastructure', 250, 'UPI', 'Need', 'Quick needs'),
  tx('29 Mar 2026', 'Street food outing', 'Lifestyle Enjoyment', 350, 'Cash', 'Want', 'Chaat + kulfi'),
  tx('29 Mar 2026', 'MR PAN SHOP', 'Lifestyle Enjoyment', 40, 'UPI', 'Want', ''),
  tx('29 Mar 2026', 'Transfer to Nimmagadda Bhavani Prasad', 'Relationships & Generosity', 50, 'UPI', 'Want', ''),
  tx('30 Mar 2026', 'Medicine refill', 'Life Infrastructure', 450, 'Cash', 'Need', 'Monthly meds'),
  tx('30 Mar 2026', 'Uber', 'Life Infrastructure', 150, 'UPI', 'Need', 'Commute'),
  tx('30 Mar 2026', 'Chai tapri', 'Lifestyle Enjoyment', 30, 'Cash', 'Want', 'Morning chai'),
  tx('30 Mar 2026', 'Vivek - HIGHRADIUS payment', 'Performance & Growth', 250, 'UPI', 'Need', ''),
  tx('30 Mar 2026', 'Transfer to Veeresh', 'Relationships & Generosity', 35, 'UPI', 'Want', ''),
  tx('30 Mar 2026', 'Transfer to Manoj HRC', 'Relationships & Generosity', 800, 'UPI', 'Want', ''),
  tx('30 Mar 2026', 'Transfer to Mohammad Irshad Qureshi', 'Relationships & Generosity', 65, 'UPI', 'Want', ''),
  tx('31 Mar 2026', 'Electricity deposit', 'Life Infrastructure', 500, 'UPI', 'Need', 'Security deposit'),
  tx('31 Mar 2026', 'Swiggy dinner', 'Lifestyle Enjoyment', 380, 'UPI', 'Want', 'Month end treat'),
  tx('31 Mar 2026', 'Auto', 'Life Infrastructure', 50, 'Cash', 'Need', 'Short ride'),
  tx('31 Mar 2026', 'Savings to account', 'Future Me', 200, 'UPI', 'Saving', ''),
  tx('31 Mar 2026', 'Transfer to Naresh K', 'Relationships & Generosity', 80, 'UPI', 'Want', ''),
  tx('31 Mar 2026', 'Transfer to Gaddam Jayakrishna', 'Relationships & Generosity', 67, 'UPI', 'Want', ''),

  // ── April 2026 ───────────────────────────────────────────────────────
  tx('01 Apr 2026', 'House Rent', 'Life Infrastructure', 12000, 'Bank Transfer', 'Need', 'Monthly rent'),
  tx('01 Apr 2026', 'Groceries - BigBasket', 'Life Infrastructure', 1700, 'UPI', 'Need', 'Monthly stock'),
  tx('01 Apr 2026', 'Chai tapri', 'Lifestyle Enjoyment', 30, 'Cash', 'Want', 'Morning chai'),
  tx('01 Apr 2026', 'Canteen lunch', 'Lifestyle Enjoyment', 120, 'Cash', 'Want', 'Office'),
  tx('01 Apr 2026', 'Credit card bill payment', 'Life Infrastructure', 4312, 'UPI', 'Need', ''),
  tx('01 Apr 2026', 'Uber India', 'Life Infrastructure', 63, 'UPI', 'Need', ''),
  tx('01 Apr 2026', 'Savings to Anuj', 'Future Me', 55000, 'UPI', 'Saving', ''),
  tx('01 Apr 2026', 'Transfer to Jarpala Suresh Nayak', 'Relationships & Generosity', 80, 'UPI', 'Want', ''),
  tx('01 Apr 2026', 'Transfer to Vedavyas', 'Relationships & Generosity', 280, 'UPI', 'Want', ''),
  tx('02 Apr 2026', 'Metro Card Recharge', 'Life Infrastructure', 500, 'UPI', 'Need', 'Monthly pass'),
  tx('02 Apr 2026', 'Mobile Recharge', 'Life Infrastructure', 299, 'UPI', 'Need', 'Airtel plan'),
  tx('02 Apr 2026', 'Swiggy dinner', 'Lifestyle Enjoyment', 280, 'UPI', 'Want', 'Quick dinner'),
  tx('02 Apr 2026', 'Transfer to Rahul Kumar', 'Relationships & Generosity', 75, 'UPI', 'Want', ''),
  tx('02 Apr 2026', 'Transfer to K Nikhil', 'Relationships & Generosity', 60, 'UPI', 'Want', ''),
  tx('03 Apr 2026', 'Gym Membership', 'Performance & Growth', 1500, 'Debit Card', 'Need', 'Monthly gym'),
  tx('03 Apr 2026', 'Coffee - Third Wave', 'Lifestyle Enjoyment', 280, 'UPI', 'Want', 'Friday coffee'),
  tx('03 Apr 2026', 'Zomato dinner', 'Lifestyle Enjoyment', 400, 'UPI', 'Want', 'Friday night'),
  tx('03 Apr 2026', 'Transfer to Mr Brijkishor Sharma', 'Relationships & Generosity', 81, 'UPI', 'Want', ''),
  tx('03 Apr 2026', 'Transfer to Korolla Naresh', 'Relationships & Generosity', 60, 'UPI', 'Want', ''),
  tx('04 Apr 2026', 'SIP - Mutual Fund', 'Future Me', 5000, 'Bank Transfer', 'Saving', 'Monthly SIP on time'),
  tx('04 Apr 2026', 'Groceries - DMart', 'Life Infrastructure', 1100, 'Cash', 'Need', 'Weekly buy'),
  tx('04 Apr 2026', 'Cafe with friends', 'Lifestyle Enjoyment', 380, 'UPI', 'Want', 'Saturday hangout'),
  tx('04 Apr 2026', 'Auto rides', 'Life Infrastructure', 100, 'Cash', 'Need', 'Market trip'),
  tx('04 Apr 2026', 'Savings to Ankush', 'Future Me', 5000, 'UPI', 'Saving', ''),
  tx('04 Apr 2026', 'Savings to Anuj', 'Future Me', 1250, 'UPI', 'Saving', ''),
  tx('04 Apr 2026', 'Savings to Nandani', 'Future Me', 1250, 'UPI', 'Saving', ''),
  tx('05 Apr 2026', 'Netflix', 'Lifestyle Enjoyment', 199, 'Credit Card', 'Want', 'Monthly sub'),
  tx('05 Apr 2026', 'Spotify', 'Lifestyle Enjoyment', 119, 'Credit Card', 'Want', 'Monthly sub'),
  tx('05 Apr 2026', 'Swiggy lunch', 'Lifestyle Enjoyment', 250, 'UPI', 'Want', 'Lazy Sunday'),
  tx('05 Apr 2026', 'Laundry', 'Life Infrastructure', 200, 'UPI', 'Need', 'Dry cleaning'),
  tx('05 Apr 2026', 'Ratnadeep Supermarket', 'Life Infrastructure', 124, 'UPI', 'Need', ''),
  tx('05 Apr 2026', 'Transfer to Dinesh Bhai', 'Relationships & Generosity', 300, 'UPI', 'Want', ''),
  tx('05 Apr 2026', 'Transfer to A Thirmal Sagar', 'Relationships & Generosity', 153, 'UPI', 'Want', ''),
  tx('06 Apr 2026', 'Electricity Bill', 'Life Infrastructure', 1350, 'UPI', 'Need', 'April bill'),
  tx('06 Apr 2026', 'Uber to office', 'Life Infrastructure', 180, 'UPI', 'Need', 'Monday rush'),
  tx('06 Apr 2026', 'Chai + samosa', 'Lifestyle Enjoyment', 50, 'Cash', 'Want', 'Break time'),
  tx('06 Apr 2026', 'Transfer to Veedhi Veeravenkata Sai Ram', 'Relationships & Generosity', 100, 'UPI', 'Want', ''),
  tx('06 Apr 2026', 'Transfer to Mandla Baleshwary', 'Relationships & Generosity', 36, 'UPI', 'Want', ''),
  tx('07 Apr 2026', 'Petrol', 'Life Infrastructure', 750, 'Debit Card', 'Need', 'Bike fuel'),
  tx('07 Apr 2026', 'Groceries - Zepto', 'Life Infrastructure', 380, 'UPI', 'Need', 'Fruits veggies'),
  tx('07 Apr 2026', 'Canteen lunch', 'Lifestyle Enjoyment', 130, 'Cash', 'Want', 'Thali'),
  tx('07 Apr 2026', 'SWIGGY order', 'Lifestyle Enjoyment', 113, 'UPI', 'Want', ''),
  tx('07 Apr 2026', 'Transfer to Asit Mondal', 'Relationships & Generosity', 76, 'UPI', 'Want', ''),
  tx('07 Apr 2026', 'Transfer to Chowdary V', 'Relationships & Generosity', 300, 'UPI', 'Want', ''),
  tx('07 Apr 2026', 'Transfer to Chowdary V (2)', 'Relationships & Generosity', 185, 'UPI', 'Want', ''),
  tx('07 Apr 2026', 'Transfer to Etikala Karthik', 'Relationships & Generosity', 60, 'UPI', 'Want', ''),
  tx('08 Apr 2026', 'Internet Bill', 'Life Infrastructure', 799, 'UPI', 'Need', 'Broadband'),
  tx('08 Apr 2026', 'Dinner with colleague', 'Relationships & Generosity', 500, 'UPI', 'Want', 'Farewell dinner'),
  tx('08 Apr 2026', 'Chai tapri', 'Lifestyle Enjoyment', 30, 'Cash', 'Want', 'Evening chai'),
  tx('08 Apr 2026', 'Transfer to Hamilpur Seema', 'Relationships & Generosity', 90, 'UPI', 'Want', ''),
  tx('08 Apr 2026', 'Transfer to Amlesh Kumar', 'Relationships & Generosity', 61, 'UPI', 'Want', ''),
  tx('09 Apr 2026', 'Hayagreeva PG Rent', 'Life Infrastructure', 9500, 'UPI', 'Need', 'Monthly PG rent'),
  tx('09 Apr 2026', 'Uber rides', 'Life Infrastructure', 200, 'UPI', 'Need', 'Commute'),
  tx('09 Apr 2026', 'Swiggy lunch', 'Lifestyle Enjoyment', 220, 'UPI', 'Want', 'Office order'),
  tx('09 Apr 2026', 'Vijaya Diagnostic Centre', 'Life Infrastructure', 200, 'UPI', 'Need', 'Medical test'),
  tx('09 Apr 2026', 'Transfer to Ravana Prathap', 'Relationships & Generosity', 75, 'UPI', 'Want', ''),
  tx('09 Apr 2026', 'Transfer to K Srikanth Reddy', 'Relationships & Generosity', 60, 'UPI', 'Want', ''),
  tx('10 Apr 2026', 'PPF Contribution', 'Future Me', 2000, 'Bank Transfer', 'Saving', 'Monthly PPF'),
  tx('10 Apr 2026', 'Dinner out', 'Lifestyle Enjoyment', 750, 'Credit Card', 'Want', 'Friday dinner'),
  tx('10 Apr 2026', 'Uber', 'Life Infrastructure', 250, 'UPI', 'Need', 'Cab home'),
  tx('10 Apr 2026', 'Uber India', 'Life Infrastructure', 59, 'UPI', 'Need', ''),
  tx('10 Apr 2026', 'Savings to Nandani', 'Future Me', 20000, 'UPI', 'Saving', ''),
  tx('10 Apr 2026', 'Transfer to Dinesh Bhai', 'Relationships & Generosity', 690, 'UPI', 'Want', ''),
  tx('10 Apr 2026', 'Transfer to Anusuri Srinivas', 'Relationships & Generosity', 61, 'UPI', 'Want', ''),
  tx('11 Apr 2026', 'Computer Bazar - laptop', 'Performance & Growth', 60000, 'UPI', 'Need', 'New laptop purchase'),
  tx('11 Apr 2026', 'Computer Bazar - accessories', 'Performance & Growth', 34500, 'UPI', 'Need', 'Laptop accessories'),
  tx('11 Apr 2026', 'Groceries - BigBasket', 'Life Infrastructure', 900, 'UPI', 'Need', 'Restock'),
  tx('11 Apr 2026', 'Movie + snacks', 'Lifestyle Enjoyment', 700, 'UPI', 'Want', 'Weekend movie'),
  tx('11 Apr 2026', 'Zomato dinner', 'Lifestyle Enjoyment', 450, 'UPI', 'Want', 'Post movie food'),
  tx('11 Apr 2026', 'Uber rides', 'Life Infrastructure', 280, 'UPI', 'Need', 'Mall trip'),
  tx('11 Apr 2026', 'Transfer to B Naveen', 'Relationships & Generosity', 325, 'UPI', 'Want', ''),
  tx('12 Apr 2026', 'FD Deposit', 'Future Me', 3000, 'Bank Transfer', 'Saving', 'Quarterly FD'),
  tx('12 Apr 2026', 'Brunch out', 'Lifestyle Enjoyment', 600, 'UPI', 'Want', 'Sunday brunch'),
  tx('12 Apr 2026', 'Groceries - Zepto', 'Life Infrastructure', 300, 'UPI', 'Need', 'Quick essentials'),
  tx('12 Apr 2026', 'Chai tapri', 'Lifestyle Enjoyment', 30, 'Cash', 'Want', 'Evening chai'),
  tx('13 Apr 2026', 'ROPPEN TRANSPORTATION', 'Life Infrastructure', 112, 'UPI', 'Need', ''),
  tx('13 Apr 2026', 'Transfer to Jhansi Ratna Das', 'Relationships & Generosity', 3500, 'UPI', 'Want', ''),
  tx('13 Apr 2026', 'Transfer to Pavan Namdev Pandilwad', 'Relationships & Generosity', 30, 'UPI', 'Want', ''),
  tx('13 Apr 2026', 'Transfer to Krishna', 'Relationships & Generosity', 10490, 'UPI', 'Want', 'Large transfer'),
  tx('13 Apr 2026', 'Transfer to Dinesh Bhai', 'Relationships & Generosity', 275, 'UPI', 'Want', ''),
  tx('13 Apr 2026', 'Transfer to Naresh Kumar', 'Relationships & Generosity', 120, 'UPI', 'Want', ''),
  tx('14 Apr 2026', 'Transfer to Thota Ravi Vamshi', 'Relationships & Generosity', 95, 'UPI', 'Want', ''),
  tx('14 Apr 2026', 'Transfer to Shaik Iliyas', 'Relationships & Generosity', 66, 'UPI', 'Want', ''),
  tx('15 Apr 2026', 'Zepto Marketplace', 'Life Infrastructure', 556, 'UPI', 'Need', ''),
  tx('15 Apr 2026', 'Uber India', 'Life Infrastructure', 61, 'UPI', 'Need', ''),
  tx('15 Apr 2026', 'Transfer to Master Anil Vislawath', 'Relationships & Generosity', 185, 'UPI', 'Want', ''),
  tx('16 Apr 2026', 'Uber India', 'Life Infrastructure', 36, 'UPI', 'Need', ''),
  tx('16 Apr 2026', 'Transfer to E Pavan Goud', 'Relationships & Generosity', 128, 'UPI', 'Want', ''),
  tx('16 Apr 2026', 'Transfer to Pallo', 'Relationships & Generosity', 700, 'UPI', 'Want', ''),
  tx('17 Apr 2026', 'GST payment', 'Life Infrastructure', 220, 'UPI', 'Need', ''),
  tx('17 Apr 2026', 'VINOBA BHAVE UNIVERSITY fee 1', 'Performance & Growth', 1550, 'UPI', 'Need', ''),
  tx('17 Apr 2026', 'VINOBA BHAVE UNIVERSITY fee 2', 'Performance & Growth', 1550, 'UPI', 'Need', ''),
  tx('17 Apr 2026', 'DE NAASTA FOODS', 'Lifestyle Enjoyment', 269, 'UPI', 'Want', ''),
  tx('17 Apr 2026', 'Uber India', 'Life Infrastructure', 84, 'UPI', 'Need', ''),
  tx('17 Apr 2026', 'Transfer to Bhagwati', 'Relationships & Generosity', 10, 'UPI', 'Want', ''),
  tx('17 Apr 2026', 'Transfer to Karnati Satish', 'Relationships & Generosity', 170, 'UPI', 'Want', ''),
  tx('17 Apr 2026', 'Transfer to Mohammed Ali', 'Relationships & Generosity', 70, 'UPI', 'Want', ''),
  tx('19 Apr 2026', 'Groceries - Zepto', 'Life Infrastructure', 280, 'UPI', 'Need', ''),
  tx('20 Apr 2026', 'Savings to Nandani', 'Future Me', 1500, 'UPI', 'Saving', ''),
  tx('20 Apr 2026', 'Transfer to Bantanahal Shankar', 'Relationships & Generosity', 90, 'UPI', 'Want', ''),
  tx('20 Apr 2026', 'Transfer to Anil Karampuri', 'Relationships & Generosity', 55, 'UPI', 'Want', ''),
  tx('21 Apr 2026', 'Uber India', 'Life Infrastructure', 76, 'UPI', 'Need', ''),
  tx('21 Apr 2026', 'Transfer to Mohd Muzaffar Khan', 'Relationships & Generosity', 60, 'UPI', 'Want', ''),
  tx('22 Apr 2026', 'M Narsimha Barbershop', 'Lifestyle Enjoyment', 920, 'UPI', 'Want', ''),
  tx('22 Apr 2026', 'Uber India', 'Life Infrastructure', 93, 'UPI', 'Need', ''),
  tx('22 Apr 2026', 'Transfer to Sonu Kumar Guptha', 'Relationships & Generosity', 50, 'UPI', 'Want', ''),
  tx('23 Apr 2026', 'Savings to Ankush', 'Future Me', 100, 'UPI', 'Saving', ''),
  tx('23 Apr 2026', 'Savings to Jafar', 'Future Me', 256, 'UPI', 'Saving', ''),
  tx('23 Apr 2026', 'Transfer to Korlakunta Ranjith Kumar', 'Relationships & Generosity', 450, 'UPI', 'Want', ''),
  tx('26 Apr 2026', 'Savings to Vikash Bhaiya', 'Future Me', 7500, 'UPI', 'Saving', ''),
  tx('26 Apr 2026', 'LAXMI MEDICAL - medicines', 'Life Infrastructure', 13, 'UPI', 'Need', ''),
  tx('26 Apr 2026', 'LAXMI MEDICAL - prescriptions', 'Life Infrastructure', 900, 'UPI', 'Need', ''),
  tx('26 Apr 2026', 'The Divine Family Salon', 'Lifestyle Enjoyment', 280, 'UPI', 'Want', ''),
  tx('26 Apr 2026', 'MS Street Coffee Cafe', 'Lifestyle Enjoyment', 330, 'UPI', 'Want', ''),
  tx('26 Apr 2026', 'Cosmetics Hub', 'Lifestyle Enjoyment', 300, 'UPI', 'Want', ''),
  tx('26 Apr 2026', 'Mittra Khadi Bhandar', 'Lifestyle Enjoyment', 3500, 'UPI', 'Want', 'Clothes shopping'),
  tx('26 Apr 2026', 'Transfer to Santosh General Store', 'Relationships & Generosity', 265, 'UPI', 'Want', ''),
  tx('26 Apr 2026', 'Transfer to Praween Shahin', 'Relationships & Generosity', 400, 'UPI', 'Want', ''),
  tx('26 Apr 2026', 'Transfer to MS Sujit Kumar', 'Relationships & Generosity', 520, 'UPI', 'Want', ''),
  tx('27 Apr 2026', 'Netflix subscription', 'Lifestyle Enjoyment', 199, 'UPI', 'Want', 'Monthly sub'),
  tx('28 Apr 2026', 'Savings to Anuj', 'Future Me', 2000, 'UPI', 'Saving', ''),
  tx('28 Apr 2026', 'Savings to account', 'Future Me', 200, 'UPI', 'Saving', ''),
  tx('28 Apr 2026', 'Transfer to Ganesh General Store', 'Relationships & Generosity', 20, 'UPI', 'Want', ''),
  tx('30 Apr 2026', 'W3HOST DIGITAL SERVICES', 'Performance & Growth', 582, 'UPI', 'Need', 'Web hosting'),
  tx('30 Apr 2026', 'Savings transfer', 'Future Me', 20000, 'UPI', 'Saving', ''),
  tx('30 Apr 2026', 'Savings to Anuj (1)', 'Future Me', 600, 'UPI', 'Saving', ''),
  tx('30 Apr 2026', 'Savings to Anuj (2)', 'Future Me', 560, 'UPI', 'Saving', ''),
  tx('30 Apr 2026', 'Transfer to Naynish Jain', 'Relationships & Generosity', 604, 'UPI', 'Want', ''),

  // ── May 2026 ─────────────────────────────────────────────────────────
  tx('01 May 2026', 'Maa Laxmi Bhandar - groceries', 'Life Infrastructure', 580, 'UPI', 'Need', ''),
  tx('01 May 2026', 'Savings to Anuj', 'Future Me', 210, 'UPI', 'Saving', ''),
  tx('01 May 2026', 'Savings to Vikash Bhaiya', 'Future Me', 7000, 'UPI', 'Saving', ''),
  tx('01 May 2026', 'RAM MISTHAN BHANDAR - sweets', 'Lifestyle Enjoyment', 100, 'UPI', 'Want', ''),
  tx('01 May 2026', 'Lalu Hotel', 'Lifestyle Enjoyment', 350, 'UPI', 'Want', ''),
  tx('02 May 2026', 'Raju Vegetable vendor', 'Life Infrastructure', 65, 'UPI', 'Need', ''),
  tx('02 May 2026', 'PARIKARMA VEGITABLES', 'Life Infrastructure', 30, 'UPI', 'Need', ''),
  tx('02 May 2026', 'Fruits shop', 'Life Infrastructure', 160, 'UPI', 'Need', ''),
  tx('02 May 2026', 'V MART HAZARIBAGH - clothes', 'Lifestyle Enjoyment', 2402, 'UPI', 'Want', 'Clothing haul'),
  tx('02 May 2026', 'Sanjay Chat Dukan', 'Lifestyle Enjoyment', 90, 'UPI', 'Want', ''),
  tx('02 May 2026', 'RD RETAILS - shopping', 'Lifestyle Enjoyment', 1606, 'UPI', 'Want', ''),
  tx('02 May 2026', 'Cosmetics Hub', 'Lifestyle Enjoyment', 750, 'UPI', 'Want', ''),
  tx('02 May 2026', 'ANURAG APPAREL - clothes', 'Lifestyle Enjoyment', 2037, 'UPI', 'Want', ''),
  tx('02 May 2026', 'FACTORY OUTLET - clothes', 'Lifestyle Enjoyment', 424, 'UPI', 'Want', ''),
  tx('02 May 2026', 'Transfer to Mahadev Parsd', 'Relationships & Generosity', 70, 'UPI', 'Want', ''),
  tx('03 May 2026', 'Zepto Marketplace', 'Life Infrastructure', 554, 'UPI', 'Need', ''),
  tx('03 May 2026', 'Dominos Pizza', 'Lifestyle Enjoyment', 296, 'UPI', 'Want', ''),
  tx('03 May 2026', 'Savings to Nandani', 'Future Me', 1000, 'UPI', 'Saving', ''),
  tx('03 May 2026', 'Savings to Anuj', 'Future Me', 1000, 'UPI', 'Saving', ''),
  tx('03 May 2026', 'Transfer to Ravi Dekka', 'Relationships & Generosity', 640, 'UPI', 'Want', ''),
  tx('04 May 2026', 'Transfer to Sabavath Tulasiram', 'Relationships & Generosity', 170, 'UPI', 'Want', ''),
  tx('04 May 2026', 'Transfer to Vinita Kumari', 'Relationships & Generosity', 15000, 'UPI', 'Want', 'Large transfer'),
  tx('04 May 2026', 'Transfer to Vijay Kumar', 'Relationships & Generosity', 50, 'UPI', 'Want', ''),
  tx('05 May 2026', 'Uber India', 'Life Infrastructure', 77, 'UPI', 'Need', ''),
  tx('05 May 2026', 'Mobile Samrat Repairing - repair', 'Performance & Growth', 2500, 'UPI', 'Need', 'Phone repair'),
  tx('05 May 2026', 'Transfer to Peethani Sunil Kumar', 'Relationships & Generosity', 52, 'UPI', 'Want', ''),
  tx('06 May 2026', 'Shadowfax delivery charges', 'Life Infrastructure', 80, 'UPI', 'Need', ''),
  tx('06 May 2026', 'Uber India', 'Life Infrastructure', 62, 'UPI', 'Need', ''),
  tx('07 May 2026', 'Transfer to Sunkara Abhinava Sai', 'Relationships & Generosity', 75, 'UPI', 'Want', ''),
  tx('07 May 2026', 'Transfer to Pradip Phukan', 'Relationships & Generosity', 61, 'UPI', 'Want', ''),
  tx('08 May 2026', 'Transfer to Telugu Shiva Shankar', 'Relationships & Generosity', 91, 'UPI', 'Want', ''),
  tx('08 May 2026', 'Transfer to Guvvali Chandu', 'Relationships & Generosity', 63, 'UPI', 'Want', ''),
  tx('09 May 2026', 'ARKA JAIN UNIVERSITY fee', 'Performance & Growth', 12000, 'UPI', 'Need', 'University fees'),
  tx('09 May 2026', 'Zepto groceries', 'Life Infrastructure', 161, 'UPI', 'Need', ''),
  tx('09 May 2026', 'Savings transfer', 'Future Me', 20000, 'UPI', 'Saving', ''),
];

export async function loadTransactions(): Promise<Transaction[]> {
  try {
    // Version-based migration: if version doesn't match, reload with latest data
    const storedVersion = await AsyncStorage.getItem(STORAGE_VERSION_KEY);
    if (storedVersion !== CURRENT_VERSION) {
      await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(SAMPLE_TRANSACTIONS));
      await AsyncStorage.setItem(STORAGE_VERSION_KEY, CURRENT_VERSION);
      return SAMPLE_TRANSACTIONS;
    }
    const data = await AsyncStorage.getItem(STORAGE_KEY);
    if (data) {
      const parsed = JSON.parse(data);
      if (Array.isArray(parsed) && parsed.length > 0) return parsed;
    }
    await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(SAMPLE_TRANSACTIONS));
    return SAMPLE_TRANSACTIONS;
  } catch {
    return SAMPLE_TRANSACTIONS;
  }
}

export async function saveTransactions(transactions: Transaction[]): Promise<void> {
  await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(transactions));
  await AsyncStorage.setItem(STORAGE_VERSION_KEY, CURRENT_VERSION);
}

export function createTransaction(data: Omit<Transaction, 'id'>): Transaction {
  return { ...data, id: generateId() };
}
